// Code generated by goctl. DO NOT EDIT.
package types

type TokenReq struct {
	UserId   int64  `json:"userId"`
	Password string `json:"password"`
}

type TokenResp struct {
	Token JwtToken `json:"token"`
	CommonResp
}

type CommonData struct {
	Id         int64  `json:"id, optional"`          // 编号
	CreateBy   string `json:"createBy, optional"`    // 创建人
	UpdateBy   string `json:"updateBy, optional"`    // 更新人
	CreateTime int64  `json:"createTime, optional"`  // 创建时间，go-zero 会自动计算
	UpdateTime int64  `json:"updateTime, optional"`  // 更新时间，go-zero 会自动计算
	DeleteBy   string `json:"deleteBy, optional"`    // 删除人
	DeleteTime int64  `json:"deleteTime, optional"`  // 删除时间
	DeleteFlag int64  `json:"deleteFlag, default=0"` // 是否删除 -1: 已删除 0: 正常
}

type CommonResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type CommonListReq struct {
	Current  int64 `form:"current"`  // 前分页号码
	PageSize int64 `form:"pageSize"` // 分页大小
}

type CommonListResp struct {
	Current  int64 `json:"current"`  // 当前分页号码
	PageSize int64 `json:"pageSize"` // 分页大小
	Success  bool  `json:"success"`  // 返回状态
	Total    int64 `json:"total"`    // 总计数量
}

type JwtToken struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type ConfigData struct {
	Value       string `json:"value"`       // 配置数据
	Label       string `json:"label"`       // 配置名称
	Type        string `json:"type"`        // 数据类型
	Description string `json:"description"` // 配置描述
	Sort        int64  `json:"sort"`        // 排序 (升序)
	Remarks     string `json:"remarks"`     // 备注信息
	CommonData
}

type ConfigAddReq struct {
	ConfigData
}

type ConfigAddResp struct {
	CommonResp
}

type ConfigListReq struct {
	CommonListReq
}

type ConfigListResp struct {
	Data []*ConfigData `json:"data"`
	CommonListResp
}

type ConfigUpdateReq struct {
	ConfigData
}

type ConfigUpdateResp struct {
	CommonResp
}

type ConfigDeleteReq struct {
	Id int64 `json:"id"`
}

type ConfigDeleteResp struct {
	CommonResp
}

type DeptData struct {
	Name     string `json:"name"`     // 机构名称
	ParentId int64  `json:"parentId"` // 上级机构ID, 一级机构为0
	OrderNum int64  `json:"orderNum"` // 排序
	CommonData
}

type DeptAddReq struct {
	DeptData
}

type DeptAddResp struct {
	CommonResp
}

type DeptListReq struct {
	CommonListReq
}

type DeptListResp struct {
	Data []*DeptData `json:"data"`
	CommonListResp
}

type DeptUpdateReq struct {
	DeptData
}

type DeptUpdateResp struct {
	CommonResp
}

type DeptDeleteReq struct {
	Id int64 `json:"id"`
}

type DeptDeleteResp struct {
	CommonResp
}

type DictData struct {
	Value       string  `json:"value"`       // 数据值
	Label       string  `json:"label"`       // 标签名
	Type        string  `json:"type"`        // 类型
	Description string  `json:"description"` // 描述
	Sort        float64 `json:"sort"`        // 排序 (升序)
	Remarks     string  `json:"remarks"`     // 备注信息
	CommonData
}

type DictAddReq struct {
	DictData
}

type DictAddResp struct {
	CommonResp
}

type DictListReq struct {
	CommonListReq
}

type DictListResp struct {
	Data []*DictData `json:"data"`
	CommonListResp
}

type DictUpdateReq struct {
	DictData
}

type DictUpdateResp struct {
	CommonResp
}

type DictDeleteReq struct {
	Id int64 `json:"id"`
}

type DictDeleteResp struct {
	CommonResp
}

type LoginLogData struct {
	UserName string `json:"userName"` // 用户名
	Status   string `json:"status"`   // 登录状态 (online:在线, 登录初始状态; login:退出登录后将 online 置为login; logout:退出登录)
	Ip       string `json:"ip"`       // IP地址
	CommonData
}

type LoginLogListReq struct {
	CommonListReq
}

type LoginLogListResp struct {
	Data []*LoginLogData `json:"data"`
	CommonListResp
}

type LoginLogDeleteReq struct {
	Id int64 `json:"id"`
}

type LoginLogDeleteResp struct {
	CommonResp
}

type MenuData struct {
	Name     string `json:"name"`     // 菜单名称
	ParentId int64  `json:"parentId"` // 父菜单ID, 一级菜单为0
	Url      string `json:"url"`      // 菜单URL,类型: 1.普通页面 (如用户管理, /sysmodel/user) 2.嵌套完整外部页面, 以http(s)开头的链接 3.嵌套服务器页面, 使用iframe:前缀+目标URL(如SQL监控, iframe:/druid/login.html, iframe:前缀会替换成服务器地址)
	Perms    string `json:"perms"`    // 授权(多个用逗号分隔, 如: sysmodel:user:add,sysmodel:user:edit)
	Type     int64  `json:"type"`     // 类型 0: 目录 1: 菜单 2: 按钮
	Icon     string `json:"icon"`     // 菜单图标
	OrderNum int64  `json:"orderNum"` // 排序
	CommonData
}

type MenuAddReq struct {
	MenuData
}

type MenuAddResp struct {
	CommonResp
}

type MenuListReq struct {
	CommonListReq
}

type MenuListResp struct {
	Data []*MenuData `json:"data"`
	CommonListResp
}

type MenuUpdateReq struct {
	MenuData
}

type MenuUpdateResp struct {
	CommonResp
}

type MenuDeleteReq struct {
	Id int64 `json:"id"`
}

type MenuDeleteResp struct {
	CommonResp
}

type RoleData struct {
	Name   string `json:"name"`   // 角色名称
	Remark string `json:"remark"` // 备注
	CommonData
}

type RoleAddReq struct {
	RoleData
}

type RoleAddResp struct {
	CommonResp
}

type RoleListReq struct {
	CommonListReq
}

type RoleListResp struct {
	Data []*RoleData `json:"data"`
	CommonListResp
}

type RoleUpdateReq struct {
	RoleData
}

type RoleUpdateResp struct {
	CommonResp
}

type RoleDeleteReq struct {
	Id int64 `json:"id"`
}

type RoleDeleteResp struct {
	CommonResp
}

type RoleMenuIdsReq struct {
}

type RoleMenuIdsResp struct {
	CommonResp
}

type RoleMenuUpdateReq struct {
}

type RoleMenuUpdateResp struct {
	CommonResp
}

type SysLogData struct {
	UserName  string `json:"userName"`  // 用户名
	Operation string `json:"operation"` // 用户操作
	Method    string `json:"method"`    // 请求方法
	Params    string `json:"params"`    // 请求参数
	Time      int64  `json:"time"`      // 执行时长(毫秒)
	Ip        string `json:"ip"`        // IP地址
}

type SysLogListReq struct {
	CommonListReq
}

type SysLogListResp struct {
	Data []*SysLogData `json:"data"`
	CommonListResp
}

type SysLogDeleteReq struct {
	Id int64 `json:"id"`
}

type SysLogDeleteResp struct {
	CommonResp
}

type UserData struct {
	Name     string `json:"name"`               // 用户名
	NickName string `json:"nickName, optional"` // 昵称
	Avatar   string `json:"avatar, optional"`   // 头像
	Password string `json:"password"`           // 密码
	Salt     string `json:"salt"`               // 加密盐
	Email    string `json:"email, optional"`    // 邮箱
	Mobile   string `json:"mobile"`             // 手机号
	Status   int64  `json:"status, default=1"`  // 状态 0: 禁用, 1: 正常
	DeptId   int64  `json:"deptId, optional"`   // 机构ID
	CommonData
}

type UserLoginReq struct {
}

type UserLoginResp struct {
	Status           string `json:"status"`
	CurrentAuthority string `json:"currentAuthority"`
}

type UserInfoReq struct {
	ID int64 `json:"id"`
}

type UserInfoResp struct {
	Avatar string `json:"avatar"`
	Name   string `json:"name"`
}

type UserAddReq struct {
	UserData
}

type UserAddResp struct {
	CommonResp
}

type UserListReq struct {
	CommonListReq
}

type UserListResp struct {
	Data []*UserData `json:"data"`
	CommonListResp
}

type UserUpdateReq struct {
	UserData
}

type UserUpdateResp struct {
	CommonResp
}

type UserDeleteReq struct {
	ID int64 `json:"id"`
}

type UserDeleteResp struct {
	CommonResp
}

type UserRoleUpdateReq struct {
}

type UserRoleUpdateResp struct {
	CommonResp
}

type ReSetPasswordReq struct {
	Id int64 `json:"id"`
}

type ReSetPasswordResp struct {
	CommonResp
}

type UserStatusUpdateReq struct {
	Id     int64 `json:"id"`
	Status int64 `json:"status"`
}

type UserStatusUpdateResp struct {
	CommonResp
}

type MemberData struct {
	MemberLevelId         int64  `json:"memberLevelId"`                   // 会员级别 ID
	Username              string `json:"username"`                        // 用户名
	Password              string `json:"password"`                        // 密码
	Nickname              string `json:"nickname, optional"`              // 昵称
	Phone                 string `json:"phone"`                           // 手机号码
	IdNumber              string `json:"idNumber, optional"`              // 身份证号
	Status                int64  `json:"status, default=1"`               // 帐号启用状态: 0->禁用; 1->启用
	Icon                  string `json:"icon, optional"`                  // 头像
	Gender                int64  `json:"gender, default=0"`               // 性别: 0->未知; 1->男; 2->女
	Birthday              string `json:"birthday, optional"`              // 生日
	Email                 string `json:"email, optional"`                 // 电邮
	City                  string `json:"city, optional"`                  // 城市
	Job                   string `json:"job, optional"`                   // 职业
	PersonalizedSignature string `json:"personalizedSignature, optional"` // 签名
	SourceType            int64  `json:"sourceType"`                      // 来源
	Integration           int64  `json:"integration, default=0"`          // 积分值
	Growth                int64  `json:"growth, default=0"`               // 成长值
	LuckyCount            int64  `json:"luckyCount, default=0"`           // 剩余抽奖次数
	HistoryIntegration    int64  `json:"historyIntegration"`              // 历史积分数量
	CommonData
}

type MemberAddReq struct {
	MemberData
}

type MemberAddResp struct {
	CommonResp
}

type MemberListReq struct {
	CommonListReq
}

type MemberListResp struct {
	Data []*MemberData `json:"data"`
	CommonListResp
}

type MemberUpdateReq struct {
	MemberData
}

type MemberUpdateResp struct {
	CommonResp
}

type MemberDeleteReq struct {
	Id int64 `json:"id"`
}

type MemberDeleteResp struct {
	CommonResp
}

type MemberAddressData struct {
	MemberId      int64  `json:"memberId"`                 // 会员 ID
	Name          string `json:"name"`                     // 收货人名称
	PhoneNumber   string `json:"phoneNumber"`              // 电话号码
	IsDefault     bool   `json:"isDefault, default=false"` // 是否为默认
	Country       string `json:"country, default=china"`   // 国家
	Province      string `json:"province"`                 // 省
	City          string `json:"city"`                     // 市
	Region        string `json:"region"`                   // 区
	DetailAddress string `json:"detailAddress"`            // 详细地址
	PostCode      string `json:"postCode"`                 // 邮政编码
	Remark        string `json:"remark"`                   // 备注
	CommonData
}

type MemberAddressAddReq struct {
	MemberAddressData
}

type MemberAddressAddResp struct {
	CommonResp
}

type MemberAddressListReq struct {
	CommonListReq
}

type MemberAddressListResp struct {
	Data []*MemberAddressData `json:"data"`
	CommonListResp
}

type MemberAddressUpdateReq struct {
	MemberAddressData
}

type MemberAddressUpdateResp struct {
	CommonResp
}

type MemberAddressDeleteReq struct {
	Id int64 `json:"id"`
}

type MemberAddressDeleteResp struct {
	CommonResp
}

type GrowthChangeHistoryData struct {
	MemberId     int64  `json:"memberId"`     // 会员 ID
	ChangeType   int64  `json:"changeType"`   // 变更类型: 0->增加; 1->减少
	ChangeCount  int64  `json:"changeCount"`  // 变更数量
	ChangeBy     string `json:"changeBy"`     // 变更人员
	ChangeReason int64  `json:"changeReason"` // 变更原因: 0->购物; 1->管理员修改
	ChangeNote   string `json:"changeNote"`   // 变更备注
	CommonData
}

type GrowthChangeHistoryAddReq struct {
	GrowthChangeHistoryData
}

type GrowthChangeHistoryAddResp struct {
	CommonResp
}

type GrowthChangeHistoryListReq struct {
	CommonListReq
}

type GrowthChangeHistoryListResp struct {
	Data []*GrowthChangeHistoryData `json:"data"`
	CommonListResp
}

type GrowthChangeHistoryUpdateReq struct {
	GrowthChangeHistoryData
}

type GrowthChangeHistoryUpdateResp struct {
	CommonResp
}

type GrowthChangeHistoryDeleteReq struct {
	Id int64 `json:"id"`
}

type GrowthChangeHistoryDeleteResp struct {
	CommonResp
}

type IntegrationChangeHistoryData struct {
	MemberId     int64  `json:"memberId"`     // 会员 ID
	ChangeType   int64  `json:"changeType"`   // 变更类型: 0->增加; 1->减少
	ChangeCount  int64  `json:"changeCount"`  // 变更数量
	ChangeBy     string `json:"changeBy"`     // 变更人员
	ChangeReason int64  `json:"changeReason"` // 变更原因: 0->购物; 1->管理员修改
	ChangeNote   string `json:"changeNote"`   // 变更备注
	CommonData
}

type IntegrationChangeHistoryAddReq struct {
	IntegrationChangeHistoryData
}

type IntegrationChangeHistoryAddResp struct {
	CommonResp
}

type IntegrationChangeHistoryListReq struct {
	CommonListReq
}

type IntegrationChangeHistoryListResp struct {
	Data []*IntegrationChangeHistoryData `json:"data"`
	CommonListResp
}

type IntegrationChangeHistoryUpdateReq struct {
	IntegrationChangeHistoryData
}

type IntegrationChangeHistoryUpdateResp struct {
	CommonResp
}

type IntegrationChangeHistoryDeleteReq struct {
	Id int64 `json:"id"`
}

type IntegrationChangeHistoryDeleteResp struct {
	CommonResp
}

type IntegrationConsumeSettingData struct {
	DeductionPerAmount int64 `json:"deductionPerAmount"` // 每一元需要抵扣的积分数量
	MaxPercentPerOrder int64 `json:"maxPercentPerOrder"` // 每笔订单最高抵用百分比
	UseUnit            int64 `json:"useUnit"`            // 每次使用积分最小单位100
	CouponStatus       int64 `json:"couponStatus"`       // 是否可以和优惠券同用; 0->不可以; 1->可以
	CommonData
}

type IntegrationConsumeSettingAddReq struct {
	IntegrationConsumeSettingData
}

type IntegrationConsumeSettingAddResp struct {
	CommonResp
}

type IntegrationConsumeSettingListReq struct {
	CommonListReq
}

type IntegrationConsumeSettingListResp struct {
	Data []*IntegrationConsumeSettingData `json:"data"`
	CommonListResp
}

type IntegrationConsumeSettingUpdateReq struct {
	IntegrationConsumeSettingData
}

type IntegrationConsumeSettingUpdateResp struct {
	CommonResp
}

type IntegrationConsumeSettingDeleteReq struct {
	Id int64 `json:"id"`
}

type IntegrationConsumeSettingDeleteResp struct {
	CommonResp
}

type MemberLevelData struct {
	Name                  string  `json:"name"`                  // 会员级别名称
	GrowthPoint           int64   `json:"growthPoint"`           // 成长点值
	IsDefault             int64   `json:"isDefault"`             // 是否为默认等级: 0->不是; 1->是
	FreeFreightPoint      float64 `json:"freeFreightPoint"`      // 免运费标准
	CommentGrowthPoint    int64   `json:"commentGrowthPoint"`    // 每次评价获取的成长值
	PriviledgeFreeFreight int64   `json:"priviledgeFreeFreight"` // 是否有免邮特权
	PriviledgeSignIn      int64   `json:"priviledgeSignIn"`      // 是否有签到特权
	PriviledgeComment     int64   `json:"priviledgeComment"`     // 是否有评论获奖励特权
	PriviledgePromotion   int64   `json:"priviledgePromotion"`   // 是否有专享活动特权
	PriviledgeMemberPrice int64   `json:"priviledgeMemberPrice"` // 是否有会员价格特权
	PriviledgeBirthday    int64   `json:"priviledgeBirthday"`    // 是否有生日特权
	Note                  string  `json:"note"`                  // 备注
	CommonData
}

type MemberLevelAddReq struct {
	MemberLevelData
}

type MemberLevelAddResp struct {
	CommonResp
}

type MemberLevelListReq struct {
	CommonListReq
}

type MemberLevelListResp struct {
	Data []*MemberLevelData `json:"data"`
	CommonListResp
}

type MemberLevelUpdateReq struct {
	MemberLevelData
}

type MemberLevelUpdateResp struct {
	CommonResp
}

type MemberLevelDeleteReq struct {
	Id int64 `json:"id"`
}

type MemberLevelDeleteResp struct {
	CommonResp
}

type MemberLoginLogData struct {
	MemberId  int64  `json:"memberId"`  // 会员 ID
	LoginType int64  `json:"loginType"` // 登录类型: 0->PC, 1->android, 2->ios, 3->mp
	Ip        string `json:"ip"`        // IP 地址
	City      string `json:"city"`      // 城市
	Province  string `json:"province"`  // 省份
	CommonData
}

type MemberLoginLogAddReq struct {
	MemberLoginLogData
}

type MemberLoginLogAddResp struct {
	CommonResp
}

type MemberLoginLogListReq struct {
	CommonListReq
}

type MemberLoginLogListResp struct {
	Data []*MemberLoginLogData `json:"data"`
	CommonListResp
}

type MemberLoginLogUpdateReq struct {
	MemberLoginLogData
}

type MemberLoginLogUpdateResp struct {
	CommonResp
}

type MemberLoginLogDeleteReq struct {
	Id int64 `json:"id"`
}

type MemberLoginLogDeleteResp struct {
	CommonResp
}

type MemberRuleSettingData struct {
	Type              int64   `json:"type"`              // 类型: 0->积分规则; 1->成长值规则
	ContinueSignDay   int64   `json:"continueSignDay"`   // 连续签到天数
	ContinueSignPoint int64   `json:"continueSignPoint"` // 连续签到赠送数量
	ConsumePerPoint   float64 `json:"consumePerPoint"`   // 每消费多少元获取1个点
	LowOrderAmount    float64 `json:"lowOrderAmount"`    // 最低获取点数的订单金额
	MaxPointPerOrder  int64   `json:"maxPointPerOrder"`  // 每笔订单最高获取点数
	CommonData
}

type MemberRuleSettingAddReq struct {
	MemberRuleSettingData
}

type MemberRuleSettingAddResp struct {
	CommonResp
}

type MemberRuleSettingListReq struct {
	CommonListReq
}

type MemberRuleSettingListResp struct {
	Data []*MemberRuleSettingData `json:"data"`
	CommonListResp
}

type MemberRuleSettingUpdateReq struct {
	MemberRuleSettingData
}

type MemberRuleSettingUpdateResp struct {
	CommonResp
}

type MemberRuleSettingDeleteReq struct {
	Id int64 `json:"id"`
}

type MemberRuleSettingDeleteResp struct {
	CommonResp
}

type MemberStatisticsInfoData struct {
	MemberId            int64   `json:"memberId"`            // 会员ID
	ConsumeAmount       float64 `json:"consumeAmount"`       // 累计消费金额
	OrderCount          int64   `json:"orderCount"`          // 订单数量
	CouponCount         int64   `json:"couponCount"`         // 优惠券数量
	CommentCount        int64   `json:"commentCount"`        // 评价数
	ReturnOrderCount    int64   `json:"returnOrderCount"`    // 退货数量
	LoginCount          int64   `json:"loginCount"`          // 登录次数
	AttendCount         int64   `json:"attendCount"`         // 关注数量
	FansCount           int64   `json:"fansCount"`           // 粉丝数量
	CollectProductCount int64   `json:"collectProductCount"` // 收藏商品数量
	CollectSubjectCount int64   `json:"collectSubjectCount"` // 收藏主题数量
	CollectTopicCount   int64   `json:"collectTopicCount"`   // 收藏话题数量
	CollectCommentCount int64   `json:"collectCommentCount"` // 收藏评论数量
	InviteFriendCount   int64   `json:"inviteFriendCount"`   // 邀请朋友数量
	RecentOrderTime     string  `json:"recentOrderTime"`     // 最后一次下订单时间
	CommonData
}

type MemberStatisticsInfoAddReq struct {
	MemberStatisticsInfoData
}

type MemberStatisticsInfoAddResp struct {
	CommonResp
}

type MemberStatisticsInfoListReq struct {
	CommonListReq
}

type MemberStatisticsInfoListResp struct {
	Data []*MemberStatisticsInfoData `json:"data"`
	CommonListResp
}

type MemberStatisticsInfoUpdateReq struct {
	MemberStatisticsInfoData
}

type MemberStatisticsInfoUpdateResp struct {
	CommonResp
}

type MemberStatisticsInfoDeleteReq struct {
	Id int64 `json:"id"`
}

type MemberStatisticsInfoDeleteResp struct {
	CommonResp
}

type MemberTagData struct {
	Name              string  `json:"name"`
	FinishOrderCount  int64   `json:"finishOrderCount"`  // 自动打标签完成订单数量
	FinishOrderAmount float64 `json:"finishOrderAmount"` // 自动打标签完成订单金额
	CommonData
}

type MemberTagAddReq struct {
	MemberTagData
}

type MemberTagAddResp struct {
	CommonResp
}

type MemberTagListReq struct {
	CommonListReq
}

type MemberTagListResp struct {
	Data []*MemberTagData `json:"data"`
	CommonListResp
}

type MemberTagUpdateReq struct {
	MemberTagData
}

type MemberTagUpdateResp struct {
	CommonResp
}

type MemberTagDeleteReq struct {
	Id int64 `json:"id"`
}

type MemberTagDeleteResp struct {
	CommonResp
}

type MemberTaskData struct {
	Name        string `json:"name"`
	Type        int64  `json:"type"`        // 任务类型: 0->新手任务; 1->日常任务
	Growth      int64  `json:"growth"`      // 赠送成长值
	Integration int64  `json:"integration"` // 赠送积分
	CommonData
}

type MemberTaskAddReq struct {
	MemberTaskData
}

type MemberTaskAddResp struct {
	CommonResp
}

type MemberTaskListReq struct {
	CommonListReq
}

type MemberTaskListResp struct {
	Data []*MemberTaskData `json:"data"`
	CommonListResp
}

type MemberTaskUpdateReq struct {
	MemberTaskData
}

type MemberTaskUpdateResp struct {
	CommonResp
}

type MemberTaskDeleteReq struct {
	Id int64 `json:"id"`
}

type MemberTaskDeleteResp struct {
	CommonResp
}
