// Code generated by goctl. DO NOT EDIT.
package types

type CommonData struct {
	Id         int64  `json:"id, optional"`         // 编号
	CreateBy   string `json:"createBy, optional"`   // 创建人
	UpdateBy   string `json:"updateBy, optional"`   // 更新人
	DeleteBy   string `json:"deleteBy, optional"`   // 删除人
	CreateTime int64  `json:"createTime, optional"` // 创建时间，go-zero 会自动计算
	UpdateTime int64  `json:"updateTime, optional"` // 更新时间，go-zero 会自动计算
	DeleteTime int64  `json:"deleteTime, optional"` // 删除时间
	DelFlag    int64  `json:"delFlag, default=0"`   // 是否删除 -1: 已删除 0: 正常
}

type CommonResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type CommonListReq struct {
	Current  int64 `form:"current"`  // 前分页号码
	PageSize int64 `form:"pageSize"` // 分页大小
}

type CommonListResp struct {
	Current  int64 `json:"current"`  // 当前分页号码
	PageSize int64 `json:"pageSize"` // 分页大小
	Success  bool  `json:"success"`  // 返回状态
	Total    int64 `json:"total"`    // 总计数量
}

type ConfigData struct {
	Value       string `json:"value"`       // 配置数据
	Label       string `json:"label"`       // 配置名称
	Type        string `json:"type"`        // 数据类型
	Description string `json:"description"` // 配置描述
	Sort        int64  `json:"sort"`        // 排序 (升序)
	Remarks     string `json:"remarks"`     // 备注信息
	CommonData
}

type ConfigAddReq struct {
	ConfigData
}

type ConfigAddResp struct {
	CommonResp
}

type ConfigListReq struct {
	CommonListReq
}

type ConfigListResp struct {
	Data []*ConfigData `json:"data"`
	CommonListResp
}

type ConfigUpdateReq struct {
	ConfigData
}

type ConfigUpdateResp struct {
	CommonResp
}

type ConfigDeleteReq struct {
	Id int64 `json:"id"`
}

type ConfigDeleteResp struct {
	CommonResp
}

type DeptData struct {
	Name     string `json:"name"`      // 机构名称
	ParentId int64  `json:"parent_id"` // 上级机构ID, 一级机构为0
	OrderNum int64  `json:"order_num"` // 排序
	CommonData
}

type DeptAddReq struct {
	DeptData
}

type DeptAddResp struct {
	CommonResp
}

type DeptListReq struct {
	CommonListReq
}

type DeptListResp struct {
	Data []*DeptData `json:"data"`
	CommonListResp
}

type DeptUpdateReq struct {
	DeptData
}

type DeptUpdateResp struct {
	CommonResp
}

type DeptDeleteReq struct {
	Id int64 `json:"id"`
}

type DeptDeleteResp struct {
	CommonResp
}

type DictData struct {
	Value       string  `json:"value"`       // 数据值
	Label       string  `json:"label"`       // 标签名
	Type        string  `json:"type"`        // 类型
	Description string  `json:"description"` // 描述
	Sort        float64 `json:"sort"`        // 排序 (升序)
	Remarks     string  `json:"remarks"`     // 备注信息
	CommonData
}

type DictAddReq struct {
	DictData
}

type DictAddResp struct {
	CommonResp
}

type DictListReq struct {
	CommonListReq
}

type DictListResp struct {
	Data []*DictData `json:"data"`
	CommonListResp
}

type DictUpdateReq struct {
	DictData
}

type DictUpdateResp struct {
	CommonResp
}

type DictDeleteReq struct {
	Id int64 `json:"id"`
}

type DictDeleteResp struct {
	CommonResp
}

type LoginLogData struct {
	UserName string `json:"user_name"` // 用户名
	Status   string `json:"status"`    // 登录状态 (online:在线, 登录初始状态; login:退出登录后将 online 置为login; logout:退出登录)
	Ip       string `json:"ip"`        // IP地址
	CommonData
}

type LoginLogListReq struct {
	CommonListReq
}

type LoginLogListResp struct {
	Data []*LoginLogData `json:"data"`
	CommonListResp
}

type LoginLogDeleteReq struct {
	Id int64 `json:"id"`
}

type LoginLogDeleteResp struct {
	CommonResp
}

type MenuData struct {
	Name     string `json:"name"`      // 菜单名称
	ParentId int64  `json:"parent_id"` // 父菜单ID, 一级菜单为0
	Url      string `json:"url"`       // 菜单URL,类型: 1.普通页面 (如用户管理, /sysmodel/user) 2.嵌套完整外部页面, 以http(s)开头的链接 3.嵌套服务器页面, 使用iframe:前缀+目标URL(如SQL监控, iframe:/druid/login.html, iframe:前缀会替换成服务器地址)
	Perms    string `json:"perms"`     // 授权(多个用逗号分隔, 如: sysmodel:user:add,sysmodel:user:edit)
	Type     int64  `json:"type"`      // 类型 0: 目录 1: 菜单 2: 按钮
	Icon     string `json:"icon"`      // 菜单图标
	OrderNum int64  `json:"order_num"` // 排序
	CommonData
}

type MenuAddReq struct {
	MenuData
}

type MenuAddResp struct {
	CommonResp
}

type MenuListReq struct {
	CommonListReq
}

type MenuListResp struct {
	Data []*MenuData `json:"data"`
	CommonListResp
}

type MenuUpdateReq struct {
	MenuData
}

type MenuUpdateResp struct {
	CommonResp
}

type MenuDeleteReq struct {
	Id int64 `json:"id"`
}

type MenuDeleteResp struct {
	CommonResp
}

type RoleData struct {
	Name   string `json:"name"`   // 角色名称
	Remark string `json:"remark"` // 备注
	CommonData
}

type RoleAddReq struct {
	RoleData
}

type RoleAddResp struct {
	CommonResp
}

type RoleListReq struct {
	CommonListReq
}

type RoleListResp struct {
	Data []*RoleData `json:"data"`
	CommonListResp
}

type RoleUpdateReq struct {
	RoleData
}

type RoleUpdateResp struct {
	CommonResp
}

type RoleDeleteReq struct {
	Id int64 `json:"id"`
}

type RoleDeleteResp struct {
	CommonResp
}

type RoleMenuIdsReq struct {
}

type RoleMenuIdsResp struct {
	CommonResp
}

type RoleMenuUpdateReq struct {
}

type RoleMenuUpdateResp struct {
	CommonResp
}

type SysLogData struct {
	UserName  string `json:"user_name"` // 用户名
	Operation string `json:"operation"` // 用户操作
	Method    string `json:"method"`    // 请求方法
	Params    string `json:"params"`    // 请求参数
	Time      int64  `json:"time"`      // 执行时长(毫秒)
	Ip        string `json:"ip"`        // IP地址
}

type SysLogListReq struct {
	CommonListReq
}

type SysLogListResp struct {
	Data []*SysLogData `json:"data"`
	CommonListResp
}

type SysLogDeleteReq struct {
	Id int64 `json:"id"`
}

type SysLogDeleteResp struct {
	CommonResp
}

type UserData struct {
	Name     string `json:"name"`               // 用户名
	NickName string `json:"nickName, optional"` // 昵称
	Avatar   string `json:"avatar, optional"`   // 头像
	Password string `json:"password"`           // 密码
	Salt     string `json:"salt"`               // 加密盐
	Email    string `json:"email, optional"`    // 邮箱
	Mobile   string `json:"mobile"`             // 手机号
	Status   int64  `json:"status, default=1"`  // 状态 0: 禁用, 1: 正常
	DeptId   int64  `json:"deptId, optional"`   // 机构ID
	CommonData
}

type UserLoginReq struct {
}

type UserLoginResp struct {
	Status           string `json:"status"`
	CurrentAuthority string `json:"currentAuthority"`
}

type UserInfoReq struct {
	ID int64 `json:"id"`
}

type UserInfoResp struct {
	Avatar string `json:"avatar"`
	Name   string `json:"name"`
}

type UserAddReq struct {
	UserData
}

type UserAddResp struct {
	CommonResp
}

type UserListReq struct {
	Current  int64 `form:"current"`
	PageSize int64 `form:"pageSize"`
}

type UserListResp struct {
	Current  int64       `json:"current"`
	Data     []*UserData `json:"data"`
	PageSize int64       `json:"pageSize"`
	Success  bool        `json:"success"`
	Total    int64       `json:"total"`
}

type UserUpdateReq struct {
	UserData
}

type UserUpdateResp struct {
	CommonResp
}

type UserDeleteReq struct {
	ID int64 `json:"id"`
}

type UserDeleteResp struct {
	CommonResp
}

type UserRoleUpdateReq struct {
}

type UserRoleUpdateResp struct {
	CommonResp
}

type ReSetPasswordReq struct {
	Id int64 `json:"id"`
}

type ReSetPasswordResp struct {
	CommonResp
}

type UserStatusUpdateReq struct {
	Id     int64 `json:"id"`
	Status int64 `json:"status"`
}

type UserStatusUpdateResp struct {
	CommonResp
}

type MemberAddReq struct {
	MemberLevelId         int64  `json:"member_level_id"`        // 会员级别 ID
	Username              string `json:"username"`               // 用户名
	Password              string `json:"password"`               // 密码
	Nickname              string `json:"nickname"`               // 昵称
	Phone                 string `json:"phone"`                  // 手机号码
	Status                int64  `json:"status"`                 // 帐号启用状态: 0->禁用; 1->启用
	CreateTime            string `json:"create_time"`            // 注册时间
	Icon                  string `json:"icon"`                   // 头像
	Gender                int64  `json:"gender"`                 // 性别: 0->未知; 1->男; 2->女
	Birthday              string `json:"birthday"`               // 生日
	City                  string `json:"city"`                   // 所在城市
	Job                   string `json:"job"`                    // 职业
	PersonalizedSignature string `json:"personalized_signature"` // 个性签名
	SourceType            int64  `json:"source_type"`            // 用户来源
	Integration           int64  `json:"integration"`            // 积分
	Growth                int64  `json:"growth"`                 // 成长值
	LuckyCount            int64  `json:"lucky_count"`            // 剩余抽奖次数
	HistoryIntegration    int64  `json:"history_integration"`    // 历史积分数量
}

type MemberAddResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type MemberListReq struct {
	Current  int64 `form:"current"`
	PageSize int64 `form:"pageSize"`
}

type MemberData struct {
	Id                    int64  `json:"id"`
	MemberLevelId         int64  `json:"member_level_id"`        // 会员级别 ID
	Username              string `json:"username"`               // 用户名
	Password              string `json:"password"`               // 密码
	Nickname              string `json:"nickname"`               // 昵称
	Phone                 string `json:"phone"`                  // 手机号码
	Status                int64  `json:"status"`                 // 帐号启用状态:0->禁用; 1->启用
	CreateTime            string `json:"create_time"`            // 注册时间
	Icon                  string `json:"icon"`                   // 头像
	Gender                int64  `json:"gender"`                 // 性别: 0->未知; 1->男; 2->女
	Birthday              string `json:"birthday"`               // 生日
	City                  string `json:"city"`                   // 所做城市
	Job                   string `json:"job"`                    // 职业
	PersonalizedSignature string `json:"personalized_signature"` // 个性签名
	SourceType            int64  `json:"source_type"`            // 用户来源
	Integration           int64  `json:"integration"`            // 积分
	Growth                int64  `json:"growth"`                 // 成长值
	LuckyCount            int64  `json:"lucky_count"`            // 剩余抽奖次数
	HistoryIntegration    int64  `json:"history_integration"`    // 历史积分数量
}

type MemberListResp struct {
	Current  int64         `json:"current"`
	Data     []*MemberData `json:"data"`
	PageSize int64         `json:"pageSize"`
	Success  bool          `json:"success"`
	Total    int64         `json:"total"`
}

type MemberUpdateReq struct {
	Id                    int64  `json:"id"`
	MemberLevelId         int64  `json:"member_level_id"`
	Username              string `json:"username"`               // 用户名
	Password              string `json:"password"`               // 密码
	Nickname              string `json:"nickname"`               // 昵称
	Phone                 string `json:"phone"`                  // 手机号码
	Status                int64  `json:"status"`                 // 帐号启用状态:0->禁用; 1->启用
	CreateTime            string `json:"create_time"`            // 注册时间
	Icon                  string `json:"icon"`                   // 头像
	Gender                int64  `json:"gender"`                 // 性别: 0->未知; 1->男; 2->女
	Birthday              string `json:"birthday"`               // 生日
	City                  string `json:"city"`                   // 所做城市
	Job                   string `json:"job"`                    // 职业
	PersonalizedSignature string `json:"personalized_signature"` // 个性签名
	SourceType            int64  `json:"source_type"`            // 用户来源
	Integration           int64  `json:"integration"`            // 积分
	Growth                int64  `json:"growth"`                 // 成长值
	LuckyCount            int64  `json:"lucky_count"`            // 剩余抽奖次数
	HistoryIntegration    int64  `json:"history_integration"`    // 历史积分数量
}

type MemberUpdateResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type MemberDeleteReq struct {
	Id int64 `json:"id"`
}

type MemberDeleteResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type MemberAddressAddReq struct {
	MemberId      int64  `json:"member_id"`
	Name          string `json:"name"`           // 收货人名称
	PhoneNumber   string `json:"phone_number"`   // 电话号码
	DefaultStatus int64  `json:"default_status"` // 是否为默认
	PostCode      string `json:"post_code"`      // 邮政编码
	Province      string `json:"province"`       // 省份/直辖市
	City          string `json:"city"`           // 城市
	Region        string `json:"region"`         // 区
	DetailAddress string `json:"detail_address"` // 详细地址(街道)
}

type MemberAddressAddResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type MemberAddressListReq struct {
	Current  int64 `form:"current"`
	PageSize int64 `form:"pageSize"`
}

type MemberAddressData struct {
	Id            int64  `json:"id"`
	MemberId      int64  `json:"member_id"`
	Name          string `json:"name"`           // 收货人名称
	PhoneNumber   string `json:"phone_number"`   // 电话号码
	DefaultStatus int64  `json:"default_status"` // 是否为默认
	PostCode      string `json:"post_code"`      // 邮政编码
	Province      string `json:"province"`       // 省份/直辖市
	City          string `json:"city"`           // 城市
	Region        string `json:"region"`         // 区
	DetailAddress string `json:"detail_address"` // 详细地址(街道)
}

type MemberAddressListResp struct {
	Current  int64                `json:"current"`
	Data     []*MemberAddressData `json:"data"`
	PageSize int64                `json:"pageSize"`
	Success  bool                 `json:"success"`
	Total    int64                `json:"total"`
}

type MemberAddressUpdateReq struct {
	Id            int64  `json:"id"`
	MemberId      int64  `json:"member_id"`
	Name          string `json:"name"`           // 收货人名称
	PhoneNumber   string `json:"phone_number"`   // 电话号码
	DefaultStatus int64  `json:"default_status"` // 是否为默认
	PostCode      string `json:"post_code"`      // 邮政编码
	Province      string `json:"province"`       // 省份/直辖市
	City          string `json:"city"`           // 城市
	Region        string `json:"region"`         // 区
	DetailAddress string `json:"detail_address"` // 详细地址(街道)
}

type MemberAddressUpdateResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type MemberAddressDeleteReq struct {
	Id int64 `json:"id"`
}

type MemberAddressDeleteResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type GrowthChangeHistoryAddReq struct {
	MemberId    int64  `json:"member_id"`
	CreateTime  string `json:"create_time"`
	ChangeType  int64  `json:"change_type"`  // 改变类型: 0->增加; 1->减少
	ChangeCount int64  `json:"change_count"` // 积分改变数量
	OperateMan  string `json:"operate_man"`  // 操作人员
	OperateNote string `json:"operate_note"` // 操作备注
	SourceType  int64  `json:"source_type"`  // 积分来源: 0->购物; 1->管理员修改
}

type GrowthChangeHistoryAddResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type GrowthChangeHistoryListReq struct {
	Current  int64 `form:"current"`
	PageSize int64 `form:"pageSize"`
}

type GrowthChangeHistoryData struct {
	Id          int64  `json:"id"`
	MemberId    int64  `json:"member_id"`
	CreateTime  string `json:"create_time"`
	ChangeType  int64  `json:"change_type"`  // 改变类型: 0->增加; 1->减少
	ChangeCount int64  `json:"change_count"` // 积分改变数量
	OperateMan  string `json:"operate_man"`  // 操作人员
	OperateNote string `json:"operate_note"` // 操作备注
	SourceType  int64  `json:"source_type"`  // 积分来源: 0->购物; 1->管理员修改
}

type GrowthChangeHistoryListResp struct {
	Current  int64                      `json:"current"`
	Data     []*GrowthChangeHistoryData `json:"data"`
	PageSize int64                      `json:"pageSize"`
	Success  bool                       `json:"success"`
	Total    int64                      `json:"total"`
}

type GrowthChangeHistoryUpdateReq struct {
	Id          int64  `json:"id"`
	MemberId    int64  `json:"member_id"`
	CreateTime  string `json:"create_time"`
	ChangeType  int64  `json:"change_type"`  // 改变类型: 0->增加; 1->减少
	ChangeCount int64  `json:"change_count"` // 积分改变数量
	OperateMan  string `json:"operate_man"`  // 操作人员
	OperateNote string `json:"operate_note"` // 操作备注
	SourceType  int64  `json:"source_type"`  // 积分来源: 0->购物; 1->管理员修改
}

type GrowthChangeHistoryUpdateResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type GrowthChangeHistoryDeleteReq struct {
	Id int64 `json:"id"`
}

type GrowthChangeHistoryDeleteResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type IntegrationChangeHistoryAddReq struct {
	MemberId    int64  `json:"member_id"`    // 会员 ID
	CreateTime  string `json:"create_time"`  // 创建时间
	ChangeType  int64  `json:"change_type"`  // 改变类型: 0->增加; 1->减少
	ChangeCount int64  `json:"change_count"` // 积分改变数量
	OperateMan  string `json:"operate_man"`  // 操作人员
	OperateNote string `json:"operate_note"` // 操作备注
	SourceType  int64  `json:"source_type"`  // 积分来源: 0->购物; 1->管理员修改
}

type IntegrationChangeHistoryAddResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type IntegrationChangeHistoryListReq struct {
	Current  int64 `form:"current"`
	PageSize int64 `form:"pageSize"`
}

type IntegrationChangeHistoryData struct {
	Id          int64  `json:"id"`
	MemberId    int64  `json:"member_id"`    // 会员 ID
	CreateTime  string `json:"create_time"`  // 创建时间
	ChangeType  int64  `json:"change_type"`  // 改变类型: 0->增加; 1->减少
	ChangeCount int64  `json:"change_count"` // 积分改变数量
	OperateMan  string `json:"operate_man"`  // 操作人员
	OperateNote string `json:"operate_note"` // 操作备注
	SourceType  int64  `json:"source_type"`  // 积分来源: 0->购物; 1->管理员修改
}

type IntegrationChangeHistoryListResp struct {
	Current  int64                           `json:"current"`
	Data     []*IntegrationChangeHistoryData `json:"data"`
	PageSize int64                           `json:"pageSize"`
	Success  bool                            `json:"success"`
	Total    int64                           `json:"total"`
}

type IntegrationChangeHistoryUpdateReq struct {
	Id          int64  `json:"id"`
	MemberId    int64  `json:"member_id"`    // 会员 ID
	CreateTime  string `json:"create_time"`  // 创建时间
	ChangeType  int64  `json:"change_type"`  // 改变类型: 0->增加; 1->减少
	ChangeCount int64  `json:"change_count"` // 积分改变数量
	OperateMan  string `json:"operate_man"`  // 操作人员
	OperateNote string `json:"operate_note"` // 操作备注
	SourceType  int64  `json:"source_type"`  // 积分来源: 0->购物; 1->管理员修改
}

type IntegrationChangeHistoryUpdateResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type IntegrationChangeHistoryDeleteReq struct {
	Id int64 `json:"id"`
}

type IntegrationChangeHistoryDeleteResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type IntegrationConsumeSettingAddReq struct {
	DeductionPerAmount int64 `json:"deduction_per_amount"`  // 每一元需要抵扣的积分数量
	MaxPercentPerOrder int64 `json:"max_percent_per_order"` // 每笔订单最高抵用百分比
	UseUnit            int64 `json:"use_unit"`              // 每次使用积分最小单位100
	CouponStatus       int64 `json:"coupon_status"`         // 是否可以和优惠券同用; 0->不可以; 1->可以
}

type IntegrationConsumeSettingAddResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type IntegrationConsumeSettingListReq struct {
	Current  int64 `form:"current"`
	PageSize int64 `form:"pageSize"`
}

type IntegrationConsumeSettingData struct {
	Id                 int64 `json:"id"`
	DeductionPerAmount int64 `json:"deduction_per_amount"`  // 每一元需要抵扣的积分数量
	MaxPercentPerOrder int64 `json:"max_percent_per_order"` // 每笔订单最高抵用百分比
	UseUnit            int64 `json:"use_unit"`              // 每次使用积分最小单位100
	CouponStatus       int64 `json:"coupon_status"`         // 是否可以和优惠券同用; 0->不可以; 1->可以
}

type IntegrationConsumeSettingListResp struct {
	Current  int64                            `json:"current"`
	Data     []*IntegrationConsumeSettingData `json:"data"`
	PageSize int64                            `json:"pageSize"`
	Success  bool                             `json:"success"`
	Total    int64                            `json:"total"`
}

type IntegrationConsumeSettingUpdateReq struct {
	Id                 int64 `json:"id"`
	DeductionPerAmount int64 `json:"deduction_per_amount"`  // 每一元需要抵扣的积分数量
	MaxPercentPerOrder int64 `json:"max_percent_per_order"` // 每笔订单最高抵用百分比
	UseUnit            int64 `json:"use_unit"`              // 每次使用积分最小单位100
	CouponStatus       int64 `json:"coupon_status"`         // 是否可以和优惠券同用; 0->不可以; 1->可以
}

type IntegrationConsumeSettingUpdateResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type IntegrationConsumeSettingDeleteReq struct {
	Id int64 `json:"id"`
}

type IntegrationConsumeSettingDeleteResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type MemberLevelAddReq struct {
	Name                  string  `json:"name"`
	GrowthPoint           int64   `json:"growth_point"`           // 成长点值
	DefaultStatus         int64   `json:"default_status"`         // 是否为默认等级: 0->不是; 1->是
	FreeFreightPoint      float64 `json:"free_freight_point"`     // 免运费标准
	CommentGrowthPoint    int64   `json:"comment_growth_point"`   // 每次评价获取的成长值
	PriviledgeFreeFreight int64   `json:"privilege_free_freight"` // 是否有免邮特权
	PriviledgeSignIn      int64   `json:"privilege_sign_in"`      // 是否有签到特权
	PriviledgeComment     int64   `json:"privilege_comment"`      // 是否有评论获奖励特权
	PriviledgePromotion   int64   `json:"privilege_promotion"`    // 是否有专享活动特权
	PriviledgeMemberPrice int64   `json:"privilege_member_price"` // 是否有会员价格特权
	PriviledgeBirthday    int64   `json:"privilege_birthday"`     // 是否有生日特权
	Note                  string  `json:"note"`                   // 备注
}

type MemberLevelAddResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type MemberLevelListReq struct {
	Current  int64 `form:"current"`
	PageSize int64 `form:"pageSize"`
}

type MemberLevelData struct {
	Id                    int64   `json:"id"`
	Name                  string  `json:"name"`
	GrowthPoint           int64   `json:"growth_point"`           // 成长点值
	DefaultStatus         int64   `json:"default_status"`         // 是否为默认等级: 0->不是; 1->是
	FreeFreightPoint      float64 `json:"free_freight_point"`     // 免运费标准
	CommentGrowthPoint    int64   `json:"comment_growth_point"`   // 每次评价获取的成长值
	PriviledgeFreeFreight int64   `json:"privilege_free_freight"` // 是否有免邮特权
	PriviledgeSignIn      int64   `json:"privilege_sign_in"`      // 是否有签到特权
	PriviledgeComment     int64   `json:"privilege_comment"`      // 是否有评论获奖励特权
	PriviledgePromotion   int64   `json:"privilege_promotion"`    // 是否有专享活动特权
	PriviledgeMemberPrice int64   `json:"privilege_member_price"` // 是否有会员价格特权
	PriviledgeBirthday    int64   `json:"privilege_birthday"`     // 是否有生日特权
	Note                  string  `json:"note"`                   // 备注
}

type MemberLevelListResp struct {
	Current  int64              `json:"current"`
	Data     []*MemberLevelData `json:"data"`
	PageSize int64              `json:"pageSize"`
	Success  bool               `json:"success"`
	Total    int64              `json:"total"`
}

type MemberLevelUpdateReq struct {
	Id                    int64   `json:"id"`
	Name                  string  `json:"name"`
	GrowthPoint           int64   `json:"growth_point"`           // 成长点值
	DefaultStatus         int64   `json:"default_status"`         // 是否为默认等级: 0->不是; 1->是
	FreeFreightPoint      float64 `json:"free_freight_point"`     // 免运费标准
	CommentGrowthPoint    int64   `json:"comment_growth_point"`   // 每次评价获取的成长值
	PriviledgeFreeFreight int64   `json:"privilege_free_freight"` // 是否有免邮特权
	PriviledgeSignIn      int64   `json:"privilege_sign_in"`      // 是否有签到特权
	PriviledgeComment     int64   `json:"privilege_comment"`      // 是否有评论获奖励特权
	PriviledgePromotion   int64   `json:"privilege_promotion"`    // 是否有专享活动特权
	PriviledgeMemberPrice int64   `json:"privilege_member_price"` // 是否有会员价格特权
	PriviledgeBirthday    int64   `json:"privilege_birthday"`     // 是否有生日特权
	Note                  string  `json:"note"`                   // 备注
}

type MemberLevelUpdateResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type MemberLevelDeleteReq struct {
	Id int64 `json:"id"`
}

type MemberLevelDeleteResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type MemberLoginLogAddReq struct {
	MemberId   int64  `json:"member_id"`
	CreateTime string `json:"create_time"`
	Ip         string `json:"ip"`
	City       string `json:"city"`
	LoginType  int64  `json:"login_type"` // 登录类型: 0->PC, 1->android, 2->ios, 3->mp
	Province   string `json:"province"`
}

type MemberLoginLogAddResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type MemberLoginLogListReq struct {
	Current  int64 `form:"current"`
	PageSize int64 `form:"pageSize"`
}

type MemberLoginLogData struct {
	Id         int64  `json:"id"`
	MemberId   int64  `json:"member_id"`   // 会员 ID
	CreateTime string `json:"create_time"` // 登录时间
	Ip         string `json:"ip"`          // IP 地址
	City       string `json:"city"`        // 城市
	LoginType  int64  `json:"login_type"`  // 登录类型: 0->登录类型: 0->PC, 1->android, 2->ios, 3->mp
	Province   string `json:"province"`    // 省份
}

type MemberLoginLogListResp struct {
	Current  int64                 `json:"current"`
	Data     []*MemberLoginLogData `json:"data"`
	PageSize int64                 `json:"pageSize"`
	Success  bool                  `json:"success"`
	Total    int64                 `json:"total"`
}

type MemberLoginLogUpdateReq struct {
	Id         int64  `json:"id"`
	MemberId   int64  `json:"member_id"`   // 会员 ID
	CreateTime string `json:"create_time"` // 登录时间
	Ip         string `json:"ip"`          // IP 地址
	City       string `json:"city"`        // 城市
	LoginType  int64  `json:"login_type"`  // 登录类型: 0->PC, 1->android, 2->ios, 3->mp
	Province   string `json:"province"`    // 省份
}

type MemberLoginLogUpdateResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type MemberLoginLogDeleteReq struct {
	Id int64 `json:"id"`
}

type MemberLoginLogDeleteResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type MemberRuleSettingAddReq struct {
	ContinueSignDay   int64   `json:"continue_sign_day"`   // 连续签到天数
	ContinueSignPoint int64   `json:"continue_sign_point"` // 连续签到赠送数量
	ConsumePerPoint   float64 `json:"consume_per_point"`   // 每消费多少元获取1个点
	LowOrderAmount    float64 `json:"low_order_amount"`    // 最低获取点数的订单金额
	MaxPointPerOrder  int64   `json:"max_point_per_order"` // 每笔订单最高获取点数
	Type              int64   `json:"type"`                // 类型: 0->积分规则; 1->成长值规则
}

type MemberRuleSettingAddResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type MemberRuleSettingListReq struct {
	Current  int64 `form:"current"`
	PageSize int64 `form:"pageSize"`
}

type MemberRuleSettingData struct {
	Id                int64   `json:"id"`
	ContinueSignDay   int64   `json:"continue_sign_day"`   // 连续签到天数
	ContinueSignPoint int64   `json:"continue_sign_point"` // 连续签到赠送数量
	ConsumePerPoint   float64 `json:"consume_per_point"`   // 每消费多少元获取1个点
	LowOrderAmount    float64 `json:"low_order_amount"`    // 最低获取点数的订单金额
	MaxPointPerOrder  int64   `json:"max_point_per_order"` // 每笔订单最高获取点数
	Type              int64   `json:"type"`                // 类型: 0->积分规则; 1->成长值规则
}

type MemberRuleSettingListResp struct {
	Current  int64                    `json:"current"`
	Data     []*MemberRuleSettingData `json:"data"`
	PageSize int64                    `json:"pageSize"`
	Success  bool                     `json:"success"`
	Total    int64                    `json:"total"`
}

type MemberRuleSettingUpdateReq struct {
	Id                int64   `json:"id"`
	ContinueSignDay   int64   `json:"continue_sign_day"`   // 连续签到天数
	ContinueSignPoint int64   `json:"continue_sign_point"` // 连续签到赠送数量
	ConsumePerPoint   float64 `json:"consume_per_point"`   // 每消费多少元获取1个点
	LowOrderAmount    float64 `json:"low_order_amount"`    // 最低获取点数的订单金额
	MaxPointPerOrder  int64   `json:"max_point_per_order"` // 每笔订单最高获取点数
	Type              int64   `json:"type"`                // 类型: 0->积分规则; 1->成长值规则
}

type MemberRuleSettingUpdateResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type MemberRuleSettingDeleteReq struct {
	Id int64 `json:"id"`
}

type MemberRuleSettingDeleteResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type MemberStatisticsInfoAddReq struct {
	MemberId            int64   `json:"member_id"`
	ConsumeAmount       float64 `json:"consume_amount"`        // 累计消费金额
	OrderCount          int64   `json:"order_count"`           // 订单数量
	CouponCount         int64   `json:"coupon_count"`          // 优惠券数量
	CommentCount        int64   `json:"comment_count"`         // 评价数
	ReturnOrderCount    int64   `json:"return_order_count"`    // 退货数量
	LoginCount          int64   `json:"login_count"`           // 登录次数
	AttendCount         int64   `json:"attend_count"`          // 关注数量
	FansCount           int64   `json:"fans_count"`            // 粉丝数量
	CollectProductCount int64   `json:"collect_product_count"` // 收藏商品数量
	CollectSubjectCount int64   `json:"collect_subject_count"` // 收藏主题数量
	CollectTopicCount   int64   `json:"collect_topic_count"`   // 收藏话题数量
	CollectCommentCount int64   `json:"collect_comment_count"` // 收藏评论数量
	InviteFriendCount   int64   `json:"invite_friend_count"`   // 邀请朋友数量
	RecentOrderTime     string  `json:"recent_order_time"`     // 最后一次下订单时间
}

type MemberStatisticsInfoAddResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type MemberStatisticsInfoListReq struct {
	Current  int64 `form:"current"`
	PageSize int64 `form:"pageSize"`
}

type MemberStatisticsInfoData struct {
	Id                  int64   `json:"id"`
	MemberId            int64   `json:"member_id"`             // 会员ID
	ConsumeAmount       float64 `json:"consume_amount"`        // 累计消费金额
	OrderCount          int64   `json:"order_count"`           // 订单数量
	CouponCount         int64   `json:"coupon_count"`          // 优惠券数量
	CommentCount        int64   `json:"comment_count"`         // 评价数
	ReturnOrderCount    int64   `json:"return_order_count"`    // 退货数量
	LoginCount          int64   `json:"login_count"`           // 登录次数
	AttendCount         int64   `json:"attend_count"`          // 关注数量
	FansCount           int64   `json:"fans_count"`            // 粉丝数量
	CollectProductCount int64   `json:"collect_product_count"` // 收藏商品数量
	CollectSubjectCount int64   `json:"collect_subject_count"` // 收藏主题数量
	CollectTopicCount   int64   `json:"collect_topic_count"`   // 收藏话题数量
	CollectCommentCount int64   `json:"collect_comment_count"` // 收藏评论数量
	InviteFriendCount   int64   `json:"invite_friend_count"`   // 邀请朋友数量
	RecentOrderTime     string  `json:"recent_order_time"`     // 最后一次下订单时间
}

type MemberStatisticsInfoListResp struct {
	Current  int64                       `json:"current"`
	Data     []*MemberStatisticsInfoData `json:"data"`
	PageSize int64                       `json:"pageSize"`
	Success  bool                        `json:"success"`
	Total    int64                       `json:"total"`
}

type MemberStatisticsInfoUpdateReq struct {
	Id                  int64   `json:"id"`
	MemberId            int64   `json:"member_id"`             // 会员ID
	ConsumeAmount       float64 `json:"consume_amount"`        // 累计消费金额
	OrderCount          int64   `json:"order_count"`           // 订单数量
	CouponCount         int64   `json:"coupon_count"`          // 优惠券数量
	CommentCount        int64   `json:"comment_count"`         // 评价数
	ReturnOrderCount    int64   `json:"return_order_count"`    // 退货数量
	LoginCount          int64   `json:"login_count"`           // 登录次数
	AttendCount         int64   `json:"attend_count"`          // 关注数量
	FansCount           int64   `json:"fans_count"`            // 粉丝数量
	CollectProductCount int64   `json:"collect_product_count"` // 收藏商品数量
	CollectSubjectCount int64   `json:"collect_subject_count"` // 收藏主题数量
	CollectTopicCount   int64   `json:"collect_topic_count"`   // 收藏话题数量
	CollectCommentCount int64   `json:"collect_comment_count"` // 收藏话题数量
	InviteFriendCount   int64   `json:"invite_friend_count"`   // 邀请朋友数量
	RecentOrderTime     string  `json:"recent_order_time"`     // 最后一次下订单时间
}

type MemberStatisticsInfoUpdateResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type MemberStatisticsInfoDeleteReq struct {
	Id int64 `json:"id"`
}

type MemberStatisticsInfoDeleteResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type MemberTagAddReq struct {
	Name              string  `json:"name"`
	FinishOrderCount  int64   `json:"finish_order_count"`  // 自动打标签完成订单数量
	FinishOrderAmount float64 `json:"finish_order_amount"` // 自动打标签完成订单金额
}

type MemberTagAddResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type MemberTagListReq struct {
	Current  int64 `form:"current"`
	PageSize int64 `form:"pageSize"`
}

type MemberTagData struct {
	Id                int64   `json:"id"`
	Name              string  `json:"name"`
	FinishOrderCount  int64   `json:"finish_order_count"`  // 自动打标签完成订单数量
	FinishOrderAmount float64 `json:"finish_order_amount"` // 自动打标签完成订单金额
}

type MemberTagListResp struct {
	Current  int64            `json:"current"`
	Data     []*MemberTagData `json:"data"`
	PageSize int64            `json:"pageSize"`
	Success  bool             `json:"success"`
	Total    int64            `json:"total"`
}

type MemberTagUpdateReq struct {
	Id                int64   `json:"id"`
	Name              string  `json:"name"`
	FinishOrderCount  int64   `json:"finish_order_count"`  // 自动打标签完成订单数量
	FinishOrderAmount float64 `json:"finish_order_amount"` // 自动打标签完成订单金额
}

type MemberTagUpdateResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type MemberTagDeleteReq struct {
	Id int64 `json:"id"`
}

type MemberTagDeleteResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type MemberTaskAddReq struct {
	Name        string `json:"name"`
	Growth      int64  `json:"growth"`      // 赠送成长值
	Integration int64  `json:"integration"` // 赠送积分
	Type        int64  `json:"type"`        // 任务类型: 0->新手任务; 1->日常任务
}

type MemberTaskAddResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type MemberTaskListReq struct {
	Current  int64 `form:"current"`
	PageSize int64 `form:"pageSize"`
}

type MemberTaskData struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Growth      int64  `json:"growth"`      // 赠送成长值
	Integration int64  `json:"integration"` // 赠送积分
	Type        int64  `json:"type"`        // 任务类型: 0->新手任务; 1->日常任务
}

type MemberTaskListResp struct {
	Current  int64             `json:"current"`
	Data     []*MemberTaskData `json:"data"`
	PageSize int64             `json:"pageSize"`
	Success  bool              `json:"success"`
	Total    int64             `json:"total"`
}

type MemberTaskUpdateReq struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Growth      int64  `json:"growth"`      // 赠送成长值
	Integration int64  `json:"integration"` // 赠送积分
	Type        int64  `json:"type"`        // 任务类型: 0->新手任务; 1->日常任务
}

type MemberTaskUpdateResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type MemberTaskDeleteReq struct {
	Id int64 `json:"id"`
}

type MemberTaskDeleteResp struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}
