// Code generated by goctl. DO NOT EDIT!
// Source: sys.proto

//go:generate mockgen -destination ./sys_mock.go -package sysclient -source $GOFILE

package sysclient

import (
	"context"

	"zdmin/service/sys/sys"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	DeptAddResp          = sys.DeptAddResp
	SysLogDeleteResp     = sys.SysLogDeleteResp
	ConfigData           = sys.ConfigData
	ConfigDeleteReq      = sys.ConfigDeleteReq
	MenuUpdateResp       = sys.MenuUpdateResp
	DictUpdateReq        = sys.DictUpdateReq
	DictDeleteResp       = sys.DictDeleteResp
	ConfigListReq        = sys.ConfigListReq
	MenuAddResp          = sys.MenuAddResp
	MenuUpdateReq        = sys.MenuUpdateReq
	LoginLogDeleteResp   = sys.LoginLogDeleteResp
	ConfigUpdateReq      = sys.ConfigUpdateReq
	UserAddReq           = sys.UserAddReq
	UserListReq          = sys.UserListReq
	RoleDeleteResp       = sys.RoleDeleteResp
	MenuAddReq           = sys.MenuAddReq
	DeptListReq          = sys.DeptListReq
	LoginLogListReq      = sys.LoginLogListReq
	LoginLogData         = sys.LoginLogData
	SysLogData           = sys.SysLogData
	UserInfoResp         = sys.UserInfoResp
	ReSetPasswordResp    = sys.ReSetPasswordResp
	UserStatusResp       = sys.UserStatusResp
	DictListReq          = sys.DictListReq
	ConfigDeleteResp     = sys.ConfigDeleteResp
	UserDeleteResp       = sys.UserDeleteResp
	DeptUpdateResp       = sys.DeptUpdateResp
	SysLogAddResp        = sys.SysLogAddResp
	ConfigAddReq         = sys.ConfigAddReq
	ConfigUpdateResp     = sys.ConfigUpdateResp
	UserLoginReq         = sys.UserLoginReq
	MenuRoleUpdateResp   = sys.MenuRoleUpdateResp
	LoginLogListResp     = sys.LoginLogListResp
	SysLogDeleteReq      = sys.SysLogDeleteReq
	UserListResp         = sys.UserListResp
	RoleAddReq           = sys.RoleAddReq
	MenuListResp         = sys.MenuListResp
	DictUpdateResp       = sys.DictUpdateResp
	ConfigListResp       = sys.ConfigListResp
	UserLoginResp        = sys.UserLoginResp
	UserAddResp          = sys.UserAddResp
	ReSetPasswordReq     = sys.ReSetPasswordReq
	DeptData             = sys.DeptData
	SysLogListResp       = sys.SysLogListResp
	SysLogListReq        = sys.SysLogListReq
	MenuDeleteResp       = sys.MenuDeleteResp
	DictListResp         = sys.DictListResp
	LoginLogDeleteReq    = sys.LoginLogDeleteReq
	SysLogAddReq         = sys.SysLogAddReq
	ConfigRoleUpdateResp = sys.ConfigRoleUpdateResp
	UserInfoReq          = sys.UserInfoReq
	UserUpdateResp       = sys.UserUpdateResp
	DictData             = sys.DictData
	LoginLogAddReq       = sys.LoginLogAddReq
	RoleDeleteReq        = sys.RoleDeleteReq
	MenuDeleteReq        = sys.MenuDeleteReq
	DictAddReq           = sys.DictAddReq
	DeptDeleteReq        = sys.DeptDeleteReq
	UserDeleteReq        = sys.UserDeleteReq
	UserRoleUpdateReq    = sys.UserRoleUpdateReq
	UserRoleUpdateResp   = sys.UserRoleUpdateResp
	RoleData             = sys.RoleData
	ConfigRoleUpdateReq  = sys.ConfigRoleUpdateReq
	MenuListReq          = sys.MenuListReq
	UserUpdateReq        = sys.UserUpdateReq
	UserStatusReq        = sys.UserStatusReq
	RoleListReq          = sys.RoleListReq
	RoleRoleUpdateReq    = sys.RoleRoleUpdateReq
	DictDeleteReq        = sys.DictDeleteReq
	DeptUpdateReq        = sys.DeptUpdateReq
	LoginLogAddResp      = sys.LoginLogAddResp
	RoleListResp         = sys.RoleListResp
	RoleUpdateReq        = sys.RoleUpdateReq
	RoleRoleUpdateResp   = sys.RoleRoleUpdateResp
	MenuData             = sys.MenuData
	DictAddResp          = sys.DictAddResp
	DeptListResp         = sys.DeptListResp
	DeptAddReq           = sys.DeptAddReq
	DeptDeleteResp       = sys.DeptDeleteResp
	ConfigAddResp        = sys.ConfigAddResp
	UserData             = sys.UserData
	RoleAddResp          = sys.RoleAddResp
	RoleUpdateResp       = sys.RoleUpdateResp
	MenuRoleUpdateReq    = sys.MenuRoleUpdateReq

	Sys interface {
		UserLogin(ctx context.Context, in *UserLoginReq) (*UserLoginResp, error)
		UserInfo(ctx context.Context, in *UserInfoReq) (*UserInfoResp, error)
		UserAdd(ctx context.Context, in *UserAddReq) (*UserAddResp, error)
		UserList(ctx context.Context, in *UserListReq) (*UserListResp, error)
		UserUpdate(ctx context.Context, in *UserUpdateReq) (*UserUpdateResp, error)
		UserDelete(ctx context.Context, in *UserDeleteReq) (*UserDeleteResp, error)
		UserRoleUpdate(ctx context.Context, in *UserRoleUpdateReq) (*UserRoleUpdateResp, error)
		ReSetPassword(ctx context.Context, in *ReSetPasswordReq) (*ReSetPasswordResp, error)
		UserStatusUpdate(ctx context.Context, in *UserStatusReq) (*UserStatusResp, error)
		RoleAdd(ctx context.Context, in *RoleAddReq) (*RoleAddResp, error)
		RoleList(ctx context.Context, in *RoleListReq) (*RoleListResp, error)
		RoleUpdate(ctx context.Context, in *RoleUpdateReq) (*RoleUpdateResp, error)
		RoleDelete(ctx context.Context, in *RoleDeleteReq) (*RoleDeleteResp, error)
		RoleRoleUpdate(ctx context.Context, in *RoleRoleUpdateReq) (*RoleRoleUpdateResp, error)
		MenuAdd(ctx context.Context, in *MenuAddReq) (*MenuAddResp, error)
		MenuList(ctx context.Context, in *MenuListReq) (*MenuListResp, error)
		MenuUpdate(ctx context.Context, in *MenuUpdateReq) (*MenuUpdateResp, error)
		MenuDelete(ctx context.Context, in *MenuDeleteReq) (*MenuDeleteResp, error)
		MenuRoleUpdate(ctx context.Context, in *MenuRoleUpdateReq) (*MenuRoleUpdateResp, error)
		DictAdd(ctx context.Context, in *DictAddReq) (*DictAddResp, error)
		DictList(ctx context.Context, in *DictListReq) (*DictListResp, error)
		DictUpdate(ctx context.Context, in *DictUpdateReq) (*DictUpdateResp, error)
		DictDelete(ctx context.Context, in *DictDeleteReq) (*DictDeleteResp, error)
		DeptAdd(ctx context.Context, in *DeptAddReq) (*DeptAddResp, error)
		DeptList(ctx context.Context, in *DeptListReq) (*DeptListResp, error)
		DeptUpdate(ctx context.Context, in *DeptUpdateReq) (*DeptUpdateResp, error)
		DeptDelete(ctx context.Context, in *DeptDeleteReq) (*DeptDeleteResp, error)
		LoginLogAdd(ctx context.Context, in *LoginLogAddReq) (*LoginLogAddResp, error)
		LoginLogList(ctx context.Context, in *LoginLogListReq) (*LoginLogListResp, error)
		LoginLogDelete(ctx context.Context, in *LoginLogDeleteReq) (*LoginLogDeleteResp, error)
		SysLogAdd(ctx context.Context, in *SysLogAddReq) (*SysLogAddResp, error)
		SysLogList(ctx context.Context, in *SysLogListReq) (*SysLogListResp, error)
		SysLogDelete(ctx context.Context, in *SysLogDeleteReq) (*SysLogDeleteResp, error)
		ConfigAdd(ctx context.Context, in *ConfigAddReq) (*ConfigAddResp, error)
		ConfigList(ctx context.Context, in *ConfigListReq) (*ConfigListResp, error)
		ConfigUpdate(ctx context.Context, in *ConfigUpdateReq) (*ConfigUpdateResp, error)
		ConfigDelete(ctx context.Context, in *ConfigDeleteReq) (*ConfigDeleteResp, error)
		ConfigRoleUpdate(ctx context.Context, in *ConfigRoleUpdateReq) (*ConfigRoleUpdateResp, error)
	}

	defaultSys struct {
		cli zrpc.Client
	}
)

func NewSys(cli zrpc.Client) Sys {
	return &defaultSys{
		cli: cli,
	}
}

func (m *defaultSys) UserLogin(ctx context.Context, in *UserLoginReq) (*UserLoginResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.UserLogin(ctx, in)
}

func (m *defaultSys) UserInfo(ctx context.Context, in *UserInfoReq) (*UserInfoResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.UserInfo(ctx, in)
}

func (m *defaultSys) UserAdd(ctx context.Context, in *UserAddReq) (*UserAddResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.UserAdd(ctx, in)
}

func (m *defaultSys) UserList(ctx context.Context, in *UserListReq) (*UserListResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.UserList(ctx, in)
}

func (m *defaultSys) UserUpdate(ctx context.Context, in *UserUpdateReq) (*UserUpdateResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.UserUpdate(ctx, in)
}

func (m *defaultSys) UserDelete(ctx context.Context, in *UserDeleteReq) (*UserDeleteResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.UserDelete(ctx, in)
}

func (m *defaultSys) UserRoleUpdate(ctx context.Context, in *UserRoleUpdateReq) (*UserRoleUpdateResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.UserRoleUpdate(ctx, in)
}

func (m *defaultSys) ReSetPassword(ctx context.Context, in *ReSetPasswordReq) (*ReSetPasswordResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.ReSetPassword(ctx, in)
}

func (m *defaultSys) UserStatusUpdate(ctx context.Context, in *UserStatusReq) (*UserStatusResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.UserStatusUpdate(ctx, in)
}

func (m *defaultSys) RoleAdd(ctx context.Context, in *RoleAddReq) (*RoleAddResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.RoleAdd(ctx, in)
}

func (m *defaultSys) RoleList(ctx context.Context, in *RoleListReq) (*RoleListResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.RoleList(ctx, in)
}

func (m *defaultSys) RoleUpdate(ctx context.Context, in *RoleUpdateReq) (*RoleUpdateResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.RoleUpdate(ctx, in)
}

func (m *defaultSys) RoleDelete(ctx context.Context, in *RoleDeleteReq) (*RoleDeleteResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.RoleDelete(ctx, in)
}

func (m *defaultSys) RoleRoleUpdate(ctx context.Context, in *RoleRoleUpdateReq) (*RoleRoleUpdateResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.RoleRoleUpdate(ctx, in)
}

func (m *defaultSys) MenuAdd(ctx context.Context, in *MenuAddReq) (*MenuAddResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.MenuAdd(ctx, in)
}

func (m *defaultSys) MenuList(ctx context.Context, in *MenuListReq) (*MenuListResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.MenuList(ctx, in)
}

func (m *defaultSys) MenuUpdate(ctx context.Context, in *MenuUpdateReq) (*MenuUpdateResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.MenuUpdate(ctx, in)
}

func (m *defaultSys) MenuDelete(ctx context.Context, in *MenuDeleteReq) (*MenuDeleteResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.MenuDelete(ctx, in)
}

func (m *defaultSys) MenuRoleUpdate(ctx context.Context, in *MenuRoleUpdateReq) (*MenuRoleUpdateResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.MenuRoleUpdate(ctx, in)
}

func (m *defaultSys) DictAdd(ctx context.Context, in *DictAddReq) (*DictAddResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.DictAdd(ctx, in)
}

func (m *defaultSys) DictList(ctx context.Context, in *DictListReq) (*DictListResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.DictList(ctx, in)
}

func (m *defaultSys) DictUpdate(ctx context.Context, in *DictUpdateReq) (*DictUpdateResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.DictUpdate(ctx, in)
}

func (m *defaultSys) DictDelete(ctx context.Context, in *DictDeleteReq) (*DictDeleteResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.DictDelete(ctx, in)
}

func (m *defaultSys) DeptAdd(ctx context.Context, in *DeptAddReq) (*DeptAddResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.DeptAdd(ctx, in)
}

func (m *defaultSys) DeptList(ctx context.Context, in *DeptListReq) (*DeptListResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.DeptList(ctx, in)
}

func (m *defaultSys) DeptUpdate(ctx context.Context, in *DeptUpdateReq) (*DeptUpdateResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.DeptUpdate(ctx, in)
}

func (m *defaultSys) DeptDelete(ctx context.Context, in *DeptDeleteReq) (*DeptDeleteResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.DeptDelete(ctx, in)
}

func (m *defaultSys) LoginLogAdd(ctx context.Context, in *LoginLogAddReq) (*LoginLogAddResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.LoginLogAdd(ctx, in)
}

func (m *defaultSys) LoginLogList(ctx context.Context, in *LoginLogListReq) (*LoginLogListResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.LoginLogList(ctx, in)
}

func (m *defaultSys) LoginLogDelete(ctx context.Context, in *LoginLogDeleteReq) (*LoginLogDeleteResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.LoginLogDelete(ctx, in)
}

func (m *defaultSys) SysLogAdd(ctx context.Context, in *SysLogAddReq) (*SysLogAddResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.SysLogAdd(ctx, in)
}

func (m *defaultSys) SysLogList(ctx context.Context, in *SysLogListReq) (*SysLogListResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.SysLogList(ctx, in)
}

func (m *defaultSys) SysLogDelete(ctx context.Context, in *SysLogDeleteReq) (*SysLogDeleteResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.SysLogDelete(ctx, in)
}

func (m *defaultSys) ConfigAdd(ctx context.Context, in *ConfigAddReq) (*ConfigAddResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.ConfigAdd(ctx, in)
}

func (m *defaultSys) ConfigList(ctx context.Context, in *ConfigListReq) (*ConfigListResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.ConfigList(ctx, in)
}

func (m *defaultSys) ConfigUpdate(ctx context.Context, in *ConfigUpdateReq) (*ConfigUpdateResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.ConfigUpdate(ctx, in)
}

func (m *defaultSys) ConfigDelete(ctx context.Context, in *ConfigDeleteReq) (*ConfigDeleteResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.ConfigDelete(ctx, in)
}

func (m *defaultSys) ConfigRoleUpdate(ctx context.Context, in *ConfigRoleUpdateReq) (*ConfigRoleUpdateResp, error) {
	client := sys.NewSysClient(m.cli.Conn())
	return client.ConfigRoleUpdate(ctx, in)
}
