// Code generated by goctl. DO NOT EDIT!
// Source: ums.proto

//go:generate mockgen -destination ./ums_mock.go -package umsclient -source $GOFILE

package umsclient

import (
	"context"

	"zdmin/service/ums/ums"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	MemberLevelData                         = ums.MemberLevelData
	MemberStatisticsInfoListReq             = ums.MemberStatisticsInfoListReq
	MemberAddressUpdateReq                  = ums.MemberAddressUpdateReq
	MemberProductCategoryRelationListResp   = ums.MemberProductCategoryRelationListResp
	MemberReceiveAddressAddResp             = ums.MemberReceiveAddressAddResp
	MemberReceiveAddressListResp            = ums.MemberReceiveAddressListResp
	MemberProductCategoryRelationData       = ums.MemberProductCategoryRelationData
	MemberLoginLogUpdateReq                 = ums.MemberLoginLogUpdateReq
	MemberLevelListReq                      = ums.MemberLevelListReq
	MemberLoginLogUpdateResp                = ums.MemberLoginLogUpdateResp
	IntegrationConsumeSettingAddReq         = ums.IntegrationConsumeSettingAddReq
	MemberTagRelationAddReq                 = ums.MemberTagRelationAddReq
	MemberListReq                           = ums.MemberListReq
	MemberAddressListReq                    = ums.MemberAddressListReq
	GrowthChangeHistoryUpdateReq            = ums.GrowthChangeHistoryUpdateReq
	MemberTagUpdateResp                     = ums.MemberTagUpdateResp
	MemberTaskAddReq                        = ums.MemberTaskAddReq
	MemberDeleteReq                         = ums.MemberDeleteReq
	IntegrationConsumeSettingUpdateResp     = ums.IntegrationConsumeSettingUpdateResp
	MemberLevelAddResp                      = ums.MemberLevelAddResp
	MemberReceiveAddressListReq             = ums.MemberReceiveAddressListReq
	MemberReceiveAddressDeleteResp          = ums.MemberReceiveAddressDeleteResp
	MemberTaskUpdateReq                     = ums.MemberTaskUpdateReq
	GrowthChangeHistoryUpdateResp           = ums.GrowthChangeHistoryUpdateResp
	MemberStatisticsInfoAddReq              = ums.MemberStatisticsInfoAddReq
	MemberTaskAddResp                       = ums.MemberTaskAddResp
	GrowthChangeHistoryAddResp              = ums.GrowthChangeHistoryAddResp
	MemberReceiveAddressAddReq              = ums.MemberReceiveAddressAddReq
	MemberTaskListResp                      = ums.MemberTaskListResp
	MemberTagRelationListReq                = ums.MemberTagRelationListReq
	IntegrationChangeHistoryDeleteResp      = ums.IntegrationChangeHistoryDeleteResp
	MemberLoginLogData                      = ums.MemberLoginLogData
	MemberRuleSettingUpdateReq              = ums.MemberRuleSettingUpdateReq
	MemberRuleSettingDeleteResp             = ums.MemberRuleSettingDeleteResp
	MemberStatisticsInfoDeleteResp          = ums.MemberStatisticsInfoDeleteResp
	IntegrationChangeHistoryListReq         = ums.IntegrationChangeHistoryListReq
	IntegrationChangeHistoryUpdateResp      = ums.IntegrationChangeHistoryUpdateResp
	MemberProductCategoryRelationUpdateReq  = ums.MemberProductCategoryRelationUpdateReq
	MemberProductCategoryRelationUpdateResp = ums.MemberProductCategoryRelationUpdateResp
	MemberStatisticsInfoListResp            = ums.MemberStatisticsInfoListResp
	MemberAddressAddResp                    = ums.MemberAddressAddResp
	MemberLevelAddReq                       = ums.MemberLevelAddReq
	MemberLoginLogAddResp                   = ums.MemberLoginLogAddResp
	MemberTagDeleteReq                      = ums.MemberTagDeleteReq
	IntegrationConsumeSettingDeleteReq      = ums.IntegrationConsumeSettingDeleteReq
	MemberStatisticsInfoUpdateResp          = ums.MemberStatisticsInfoUpdateResp
	MemberTaskDeleteResp                    = ums.MemberTaskDeleteResp
	GrowthChangeHistoryListResp             = ums.GrowthChangeHistoryListResp
	IntegrationConsumeSettingUpdateReq      = ums.IntegrationConsumeSettingUpdateReq
	MemberLevelUpdateReq                    = ums.MemberLevelUpdateReq
	MemberLoginLogListReq                   = ums.MemberLoginLogListReq
	MemberStatisticsInfoData                = ums.MemberStatisticsInfoData
	MemberTagAddResp                        = ums.MemberTagAddResp
	MemberTaskDeleteReq                     = ums.MemberTaskDeleteReq
	GrowthChangeHistoryDeleteResp           = ums.GrowthChangeHistoryDeleteResp
	IntegrationChangeHistoryData            = ums.IntegrationChangeHistoryData
	IntegrationConsumeSettingData           = ums.IntegrationConsumeSettingData
	MemberProductCategoryRelationListReq    = ums.MemberProductCategoryRelationListReq
	MemberProductCategoryRelationDeleteResp = ums.MemberProductCategoryRelationDeleteResp
	MemberAddressDeleteResp                 = ums.MemberAddressDeleteResp
	MemberLevelListResp                     = ums.MemberLevelListResp
	MemberTagRelationUpdateResp             = ums.MemberTagRelationUpdateResp
	MemberReceiveAddressData                = ums.MemberReceiveAddressData
	MemberRuleSettingUpdateResp             = ums.MemberRuleSettingUpdateResp
	MemberStatisticsInfoDeleteReq           = ums.MemberStatisticsInfoDeleteReq
	MemberTagListReq                        = ums.MemberTagListReq
	GrowthChangeHistoryAddReq               = ums.GrowthChangeHistoryAddReq
	MemberTagRelationAddResp                = ums.MemberTagRelationAddResp
	MemberTagRelationDeleteReq              = ums.MemberTagRelationDeleteReq
	MemberReceiveAddressUpdateResp          = ums.MemberReceiveAddressUpdateResp
	IntegrationConsumeSettingListResp       = ums.IntegrationConsumeSettingListResp
	MemberTaskData                          = ums.MemberTaskData
	MemberDeleteResp                        = ums.MemberDeleteResp
	MemberUpdateReq                         = ums.MemberUpdateReq
	GrowthChangeHistoryData                 = ums.GrowthChangeHistoryData
	IntegrationChangeHistoryDeleteReq       = ums.IntegrationChangeHistoryDeleteReq
	MemberMemberTagRelationData             = ums.MemberMemberTagRelationData
	MemberTaskListReq                       = ums.MemberTaskListReq
	MemberAddResp                           = ums.MemberAddResp
	IntegrationChangeHistoryAddReq          = ums.IntegrationChangeHistoryAddReq
	MemberRuleSettingListReq                = ums.MemberRuleSettingListReq
	MemberAddressData                       = ums.MemberAddressData
	MemberStatisticsInfoUpdateReq           = ums.MemberStatisticsInfoUpdateReq
	IntegrationConsumeSettingDeleteResp     = ums.IntegrationConsumeSettingDeleteResp
	MemberRuleSettingData                   = ums.MemberRuleSettingData
	MemberAddressListResp                   = ums.MemberAddressListResp
	MemberLoginLogAddReq                    = ums.MemberLoginLogAddReq
	MemberReceiveAddressUpdateReq           = ums.MemberReceiveAddressUpdateReq
	MemberTagData                           = ums.MemberTagData
	MemberTagDeleteResp                     = ums.MemberTagDeleteResp
	MemberTaskUpdateResp                    = ums.MemberTaskUpdateResp
	GrowthChangeHistoryDeleteReq            = ums.GrowthChangeHistoryDeleteReq
	IntegrationChangeHistoryAddResp         = ums.IntegrationChangeHistoryAddResp
	IntegrationConsumeSettingListReq        = ums.IntegrationConsumeSettingListReq
	MemberLevelDeleteResp                   = ums.MemberLevelDeleteResp
	MemberTagRelationDeleteResp             = ums.MemberTagRelationDeleteResp
	MemberUpdateResp                        = ums.MemberUpdateResp
	GrowthChangeHistoryListReq              = ums.GrowthChangeHistoryListReq
	IntegrationConsumeSettingAddResp        = ums.IntegrationConsumeSettingAddResp
	MemberLevelUpdateResp                   = ums.MemberLevelUpdateResp
	MemberProductCategoryRelationAddResp    = ums.MemberProductCategoryRelationAddResp
	MemberRuleSettingDeleteReq              = ums.MemberRuleSettingDeleteReq
	MemberAddressDeleteReq                  = ums.MemberAddressDeleteReq
	MemberReceiveAddressDeleteReq           = ums.MemberReceiveAddressDeleteReq
	MemberRuleSettingAddResp                = ums.MemberRuleSettingAddResp
	IntegrationChangeHistoryUpdateReq       = ums.IntegrationChangeHistoryUpdateReq
	MemberLevelDeleteReq                    = ums.MemberLevelDeleteReq
	MemberLoginLogListResp                  = ums.MemberLoginLogListResp
	MemberTagRelationUpdateReq              = ums.MemberTagRelationUpdateReq
	MemberTagUpdateReq                      = ums.MemberTagUpdateReq
	MemberAddressUpdateResp                 = ums.MemberAddressUpdateResp
	MemberRuleSettingListResp               = ums.MemberRuleSettingListResp
	MemberTagAddReq                         = ums.MemberTagAddReq
	MemberData                              = ums.MemberData
	MemberProductCategoryRelationAddReq     = ums.MemberProductCategoryRelationAddReq
	MemberRuleSettingAddReq                 = ums.MemberRuleSettingAddReq
	MemberStatisticsInfoAddResp             = ums.MemberStatisticsInfoAddResp
	MemberTagRelationListResp               = ums.MemberTagRelationListResp
	MemberAddressAddReq                     = ums.MemberAddressAddReq
	IntegrationChangeHistoryListResp        = ums.IntegrationChangeHistoryListResp
	MemberLoginLogDeleteReq                 = ums.MemberLoginLogDeleteReq
	MemberProductCategoryRelationDeleteReq  = ums.MemberProductCategoryRelationDeleteReq
	MemberListResp                          = ums.MemberListResp
	MemberLoginLogDeleteResp                = ums.MemberLoginLogDeleteResp
	MemberTagListResp                       = ums.MemberTagListResp
	MemberAddReq                            = ums.MemberAddReq

	Ums interface {
		MemberAdd(ctx context.Context, in *MemberAddReq) (*MemberAddResp, error)
		MemberList(ctx context.Context, in *MemberListReq) (*MemberListResp, error)
		MemberUpdate(ctx context.Context, in *MemberUpdateReq) (*MemberUpdateResp, error)
		MemberDelete(ctx context.Context, in *MemberDeleteReq) (*MemberDeleteResp, error)
		MemberAddressAdd(ctx context.Context, in *MemberAddressAddReq) (*MemberAddressAddResp, error)
		MemberAddressList(ctx context.Context, in *MemberAddressListReq) (*MemberAddressListResp, error)
		MemberAddressUpdate(ctx context.Context, in *MemberAddressUpdateReq) (*MemberAddressUpdateResp, error)
		MemberAddressDelete(ctx context.Context, in *MemberAddressDeleteReq) (*MemberAddressDeleteResp, error)
		GrowthChangeHistoryAdd(ctx context.Context, in *GrowthChangeHistoryAddReq) (*GrowthChangeHistoryAddResp, error)
		GrowthChangeHistoryList(ctx context.Context, in *GrowthChangeHistoryListReq) (*GrowthChangeHistoryListResp, error)
		GrowthChangeHistoryUpdate(ctx context.Context, in *GrowthChangeHistoryUpdateReq) (*GrowthChangeHistoryUpdateResp, error)
		GrowthChangeHistoryDelete(ctx context.Context, in *GrowthChangeHistoryDeleteReq) (*GrowthChangeHistoryDeleteResp, error)
		IntegrationChangeHistoryAdd(ctx context.Context, in *IntegrationChangeHistoryAddReq) (*IntegrationChangeHistoryAddResp, error)
		IntegrationChangeHistoryList(ctx context.Context, in *IntegrationChangeHistoryListReq) (*IntegrationChangeHistoryListResp, error)
		IntegrationChangeHistoryUpdate(ctx context.Context, in *IntegrationChangeHistoryUpdateReq) (*IntegrationChangeHistoryUpdateResp, error)
		IntegrationChangeHistoryDelete(ctx context.Context, in *IntegrationChangeHistoryDeleteReq) (*IntegrationChangeHistoryDeleteResp, error)
		IntegrationConsumeSettingAdd(ctx context.Context, in *IntegrationConsumeSettingAddReq) (*IntegrationConsumeSettingAddResp, error)
		IntegrationConsumeSettingList(ctx context.Context, in *IntegrationConsumeSettingListReq) (*IntegrationConsumeSettingListResp, error)
		IntegrationConsumeSettingUpdate(ctx context.Context, in *IntegrationConsumeSettingUpdateReq) (*IntegrationConsumeSettingUpdateResp, error)
		IntegrationConsumeSettingDelete(ctx context.Context, in *IntegrationConsumeSettingDeleteReq) (*IntegrationConsumeSettingDeleteResp, error)
		MemberLevelAdd(ctx context.Context, in *MemberLevelAddReq) (*MemberLevelAddResp, error)
		MemberLevelList(ctx context.Context, in *MemberLevelListReq) (*MemberLevelListResp, error)
		MemberLevelUpdate(ctx context.Context, in *MemberLevelUpdateReq) (*MemberLevelUpdateResp, error)
		MemberLevelDelete(ctx context.Context, in *MemberLevelDeleteReq) (*MemberLevelDeleteResp, error)
		MemberLoginLogAdd(ctx context.Context, in *MemberLoginLogAddReq) (*MemberLoginLogAddResp, error)
		MemberLoginLogList(ctx context.Context, in *MemberLoginLogListReq) (*MemberLoginLogListResp, error)
		MemberLoginLogUpdate(ctx context.Context, in *MemberLoginLogUpdateReq) (*MemberLoginLogUpdateResp, error)
		MemberLoginLogDelete(ctx context.Context, in *MemberLoginLogDeleteReq) (*MemberLoginLogDeleteResp, error)
		MemberRuleSettingAdd(ctx context.Context, in *MemberRuleSettingAddReq) (*MemberRuleSettingAddResp, error)
		MemberRuleSettingList(ctx context.Context, in *MemberRuleSettingListReq) (*MemberRuleSettingListResp, error)
		MemberRuleSettingUpdate(ctx context.Context, in *MemberRuleSettingUpdateReq) (*MemberRuleSettingUpdateResp, error)
		MemberRuleSettingDelete(ctx context.Context, in *MemberRuleSettingDeleteReq) (*MemberRuleSettingDeleteResp, error)
		MemberStatisticsInfoAdd(ctx context.Context, in *MemberStatisticsInfoAddReq) (*MemberStatisticsInfoAddResp, error)
		MemberStatisticsInfoList(ctx context.Context, in *MemberStatisticsInfoListReq) (*MemberStatisticsInfoListResp, error)
		MemberStatisticsInfoUpdate(ctx context.Context, in *MemberStatisticsInfoUpdateReq) (*MemberStatisticsInfoUpdateResp, error)
		MemberStatisticsInfoDelete(ctx context.Context, in *MemberStatisticsInfoDeleteReq) (*MemberStatisticsInfoDeleteResp, error)
		MemberTagAdd(ctx context.Context, in *MemberTagAddReq) (*MemberTagAddResp, error)
		MemberTagList(ctx context.Context, in *MemberTagListReq) (*MemberTagListResp, error)
		MemberTagUpdate(ctx context.Context, in *MemberTagUpdateReq) (*MemberTagUpdateResp, error)
		MemberTagDelete(ctx context.Context, in *MemberTagDeleteReq) (*MemberTagDeleteResp, error)
		MemberTaskAdd(ctx context.Context, in *MemberTaskAddReq) (*MemberTaskAddResp, error)
		MemberTaskList(ctx context.Context, in *MemberTaskListReq) (*MemberTaskListResp, error)
		MemberTaskUpdate(ctx context.Context, in *MemberTaskUpdateReq) (*MemberTaskUpdateResp, error)
		MemberTaskDelete(ctx context.Context, in *MemberTaskDeleteReq) (*MemberTaskDeleteResp, error)
		MemberTagRelationAdd(ctx context.Context, in *MemberTagRelationAddReq) (*MemberTagRelationAddResp, error)
		MemberTagRelationList(ctx context.Context, in *MemberTagRelationListReq) (*MemberTagRelationListResp, error)
		MemberTagRelationUpdate(ctx context.Context, in *MemberTagRelationUpdateReq) (*MemberTagRelationUpdateResp, error)
		MemberTagRelationDelete(ctx context.Context, in *MemberTagRelationDeleteReq) (*MemberTagRelationDeleteResp, error)
		MemberProductCategoryRelationAdd(ctx context.Context, in *MemberProductCategoryRelationAddReq) (*MemberProductCategoryRelationAddResp, error)
		MemberProductCategoryRelationList(ctx context.Context, in *MemberProductCategoryRelationListReq) (*MemberProductCategoryRelationListResp, error)
		MemberProductCategoryRelationUpdate(ctx context.Context, in *MemberProductCategoryRelationUpdateReq) (*MemberProductCategoryRelationUpdateResp, error)
		MemberProductCategoryRelationDelete(ctx context.Context, in *MemberProductCategoryRelationDeleteReq) (*MemberProductCategoryRelationDeleteResp, error)
		MemberReceiveAddressAdd(ctx context.Context, in *MemberReceiveAddressAddReq) (*MemberReceiveAddressAddResp, error)
		MemberReceiveAddressList(ctx context.Context, in *MemberReceiveAddressListReq) (*MemberReceiveAddressListResp, error)
		MemberReceiveAddressUpdate(ctx context.Context, in *MemberReceiveAddressUpdateReq) (*MemberReceiveAddressUpdateResp, error)
		MemberReceiveAddressDelete(ctx context.Context, in *MemberReceiveAddressDeleteReq) (*MemberReceiveAddressDeleteResp, error)
	}

	defaultUms struct {
		cli zrpc.Client
	}
)

func NewUms(cli zrpc.Client) Ums {
	return &defaultUms{
		cli: cli,
	}
}

func (m *defaultUms) MemberAdd(ctx context.Context, in *MemberAddReq) (*MemberAddResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberAdd(ctx, in)
}

func (m *defaultUms) MemberList(ctx context.Context, in *MemberListReq) (*MemberListResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberList(ctx, in)
}

func (m *defaultUms) MemberUpdate(ctx context.Context, in *MemberUpdateReq) (*MemberUpdateResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberUpdate(ctx, in)
}

func (m *defaultUms) MemberDelete(ctx context.Context, in *MemberDeleteReq) (*MemberDeleteResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberDelete(ctx, in)
}

func (m *defaultUms) MemberAddressAdd(ctx context.Context, in *MemberAddressAddReq) (*MemberAddressAddResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberAddressAdd(ctx, in)
}

func (m *defaultUms) MemberAddressList(ctx context.Context, in *MemberAddressListReq) (*MemberAddressListResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberAddressList(ctx, in)
}

func (m *defaultUms) MemberAddressUpdate(ctx context.Context, in *MemberAddressUpdateReq) (*MemberAddressUpdateResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberAddressUpdate(ctx, in)
}

func (m *defaultUms) MemberAddressDelete(ctx context.Context, in *MemberAddressDeleteReq) (*MemberAddressDeleteResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberAddressDelete(ctx, in)
}

func (m *defaultUms) GrowthChangeHistoryAdd(ctx context.Context, in *GrowthChangeHistoryAddReq) (*GrowthChangeHistoryAddResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.GrowthChangeHistoryAdd(ctx, in)
}

func (m *defaultUms) GrowthChangeHistoryList(ctx context.Context, in *GrowthChangeHistoryListReq) (*GrowthChangeHistoryListResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.GrowthChangeHistoryList(ctx, in)
}

func (m *defaultUms) GrowthChangeHistoryUpdate(ctx context.Context, in *GrowthChangeHistoryUpdateReq) (*GrowthChangeHistoryUpdateResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.GrowthChangeHistoryUpdate(ctx, in)
}

func (m *defaultUms) GrowthChangeHistoryDelete(ctx context.Context, in *GrowthChangeHistoryDeleteReq) (*GrowthChangeHistoryDeleteResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.GrowthChangeHistoryDelete(ctx, in)
}

func (m *defaultUms) IntegrationChangeHistoryAdd(ctx context.Context, in *IntegrationChangeHistoryAddReq) (*IntegrationChangeHistoryAddResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.IntegrationChangeHistoryAdd(ctx, in)
}

func (m *defaultUms) IntegrationChangeHistoryList(ctx context.Context, in *IntegrationChangeHistoryListReq) (*IntegrationChangeHistoryListResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.IntegrationChangeHistoryList(ctx, in)
}

func (m *defaultUms) IntegrationChangeHistoryUpdate(ctx context.Context, in *IntegrationChangeHistoryUpdateReq) (*IntegrationChangeHistoryUpdateResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.IntegrationChangeHistoryUpdate(ctx, in)
}

func (m *defaultUms) IntegrationChangeHistoryDelete(ctx context.Context, in *IntegrationChangeHistoryDeleteReq) (*IntegrationChangeHistoryDeleteResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.IntegrationChangeHistoryDelete(ctx, in)
}

func (m *defaultUms) IntegrationConsumeSettingAdd(ctx context.Context, in *IntegrationConsumeSettingAddReq) (*IntegrationConsumeSettingAddResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.IntegrationConsumeSettingAdd(ctx, in)
}

func (m *defaultUms) IntegrationConsumeSettingList(ctx context.Context, in *IntegrationConsumeSettingListReq) (*IntegrationConsumeSettingListResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.IntegrationConsumeSettingList(ctx, in)
}

func (m *defaultUms) IntegrationConsumeSettingUpdate(ctx context.Context, in *IntegrationConsumeSettingUpdateReq) (*IntegrationConsumeSettingUpdateResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.IntegrationConsumeSettingUpdate(ctx, in)
}

func (m *defaultUms) IntegrationConsumeSettingDelete(ctx context.Context, in *IntegrationConsumeSettingDeleteReq) (*IntegrationConsumeSettingDeleteResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.IntegrationConsumeSettingDelete(ctx, in)
}

func (m *defaultUms) MemberLevelAdd(ctx context.Context, in *MemberLevelAddReq) (*MemberLevelAddResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberLevelAdd(ctx, in)
}

func (m *defaultUms) MemberLevelList(ctx context.Context, in *MemberLevelListReq) (*MemberLevelListResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberLevelList(ctx, in)
}

func (m *defaultUms) MemberLevelUpdate(ctx context.Context, in *MemberLevelUpdateReq) (*MemberLevelUpdateResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberLevelUpdate(ctx, in)
}

func (m *defaultUms) MemberLevelDelete(ctx context.Context, in *MemberLevelDeleteReq) (*MemberLevelDeleteResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberLevelDelete(ctx, in)
}

func (m *defaultUms) MemberLoginLogAdd(ctx context.Context, in *MemberLoginLogAddReq) (*MemberLoginLogAddResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberLoginLogAdd(ctx, in)
}

func (m *defaultUms) MemberLoginLogList(ctx context.Context, in *MemberLoginLogListReq) (*MemberLoginLogListResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberLoginLogList(ctx, in)
}

func (m *defaultUms) MemberLoginLogUpdate(ctx context.Context, in *MemberLoginLogUpdateReq) (*MemberLoginLogUpdateResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberLoginLogUpdate(ctx, in)
}

func (m *defaultUms) MemberLoginLogDelete(ctx context.Context, in *MemberLoginLogDeleteReq) (*MemberLoginLogDeleteResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberLoginLogDelete(ctx, in)
}

func (m *defaultUms) MemberRuleSettingAdd(ctx context.Context, in *MemberRuleSettingAddReq) (*MemberRuleSettingAddResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberRuleSettingAdd(ctx, in)
}

func (m *defaultUms) MemberRuleSettingList(ctx context.Context, in *MemberRuleSettingListReq) (*MemberRuleSettingListResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberRuleSettingList(ctx, in)
}

func (m *defaultUms) MemberRuleSettingUpdate(ctx context.Context, in *MemberRuleSettingUpdateReq) (*MemberRuleSettingUpdateResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberRuleSettingUpdate(ctx, in)
}

func (m *defaultUms) MemberRuleSettingDelete(ctx context.Context, in *MemberRuleSettingDeleteReq) (*MemberRuleSettingDeleteResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberRuleSettingDelete(ctx, in)
}

func (m *defaultUms) MemberStatisticsInfoAdd(ctx context.Context, in *MemberStatisticsInfoAddReq) (*MemberStatisticsInfoAddResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberStatisticsInfoAdd(ctx, in)
}

func (m *defaultUms) MemberStatisticsInfoList(ctx context.Context, in *MemberStatisticsInfoListReq) (*MemberStatisticsInfoListResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberStatisticsInfoList(ctx, in)
}

func (m *defaultUms) MemberStatisticsInfoUpdate(ctx context.Context, in *MemberStatisticsInfoUpdateReq) (*MemberStatisticsInfoUpdateResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberStatisticsInfoUpdate(ctx, in)
}

func (m *defaultUms) MemberStatisticsInfoDelete(ctx context.Context, in *MemberStatisticsInfoDeleteReq) (*MemberStatisticsInfoDeleteResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberStatisticsInfoDelete(ctx, in)
}

func (m *defaultUms) MemberTagAdd(ctx context.Context, in *MemberTagAddReq) (*MemberTagAddResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberTagAdd(ctx, in)
}

func (m *defaultUms) MemberTagList(ctx context.Context, in *MemberTagListReq) (*MemberTagListResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberTagList(ctx, in)
}

func (m *defaultUms) MemberTagUpdate(ctx context.Context, in *MemberTagUpdateReq) (*MemberTagUpdateResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberTagUpdate(ctx, in)
}

func (m *defaultUms) MemberTagDelete(ctx context.Context, in *MemberTagDeleteReq) (*MemberTagDeleteResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberTagDelete(ctx, in)
}

func (m *defaultUms) MemberTaskAdd(ctx context.Context, in *MemberTaskAddReq) (*MemberTaskAddResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberTaskAdd(ctx, in)
}

func (m *defaultUms) MemberTaskList(ctx context.Context, in *MemberTaskListReq) (*MemberTaskListResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberTaskList(ctx, in)
}

func (m *defaultUms) MemberTaskUpdate(ctx context.Context, in *MemberTaskUpdateReq) (*MemberTaskUpdateResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberTaskUpdate(ctx, in)
}

func (m *defaultUms) MemberTaskDelete(ctx context.Context, in *MemberTaskDeleteReq) (*MemberTaskDeleteResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberTaskDelete(ctx, in)
}

func (m *defaultUms) MemberTagRelationAdd(ctx context.Context, in *MemberTagRelationAddReq) (*MemberTagRelationAddResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberTagRelationAdd(ctx, in)
}

func (m *defaultUms) MemberTagRelationList(ctx context.Context, in *MemberTagRelationListReq) (*MemberTagRelationListResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberTagRelationList(ctx, in)
}

func (m *defaultUms) MemberTagRelationUpdate(ctx context.Context, in *MemberTagRelationUpdateReq) (*MemberTagRelationUpdateResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberTagRelationUpdate(ctx, in)
}

func (m *defaultUms) MemberTagRelationDelete(ctx context.Context, in *MemberTagRelationDeleteReq) (*MemberTagRelationDeleteResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberTagRelationDelete(ctx, in)
}

func (m *defaultUms) MemberProductCategoryRelationAdd(ctx context.Context, in *MemberProductCategoryRelationAddReq) (*MemberProductCategoryRelationAddResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberProductCategoryRelationAdd(ctx, in)
}

func (m *defaultUms) MemberProductCategoryRelationList(ctx context.Context, in *MemberProductCategoryRelationListReq) (*MemberProductCategoryRelationListResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberProductCategoryRelationList(ctx, in)
}

func (m *defaultUms) MemberProductCategoryRelationUpdate(ctx context.Context, in *MemberProductCategoryRelationUpdateReq) (*MemberProductCategoryRelationUpdateResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberProductCategoryRelationUpdate(ctx, in)
}

func (m *defaultUms) MemberProductCategoryRelationDelete(ctx context.Context, in *MemberProductCategoryRelationDeleteReq) (*MemberProductCategoryRelationDeleteResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberProductCategoryRelationDelete(ctx, in)
}

func (m *defaultUms) MemberReceiveAddressAdd(ctx context.Context, in *MemberReceiveAddressAddReq) (*MemberReceiveAddressAddResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberReceiveAddressAdd(ctx, in)
}

func (m *defaultUms) MemberReceiveAddressList(ctx context.Context, in *MemberReceiveAddressListReq) (*MemberReceiveAddressListResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberReceiveAddressList(ctx, in)
}

func (m *defaultUms) MemberReceiveAddressUpdate(ctx context.Context, in *MemberReceiveAddressUpdateReq) (*MemberReceiveAddressUpdateResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberReceiveAddressUpdate(ctx, in)
}

func (m *defaultUms) MemberReceiveAddressDelete(ctx context.Context, in *MemberReceiveAddressDeleteReq) (*MemberReceiveAddressDeleteResp, error) {
	client := ums.NewUmsClient(m.cli.Conn())
	return client.MemberReceiveAddressDelete(ctx, in)
}
